// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfl7eZMCicJY8EPZzZNUp-27qmTtnovRU',
    appId: '1:17338485793:web:2247b8dc8b63f14c6ce760',
    messagingSenderId: '17338485793',
    projectId: 'liklok-88d38',
    authDomain: 'liklok-88d38.firebaseapp.com',
    storageBucket: 'liklok-88d38.appspot.com',
    measurementId: 'G-8XN3FR5SQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7cYBR3l0oXQGEvCyFrLIeZGpQQ7yQZs',
    appId: '1:17338485793:android:cdeff308a5fd97166ce760',
    messagingSenderId: '17338485793',
    projectId: 'liklok-88d38',
    storageBucket: 'liklok-88d38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHPzLeAKPd4pyAxd0FeSiwsPjSoZybQ0',
    appId: '1:17338485793:ios:91fd85b193099a436ce760',
    messagingSenderId: '17338485793',
    projectId: 'liklok-88d38',
    storageBucket: 'liklok-88d38.appspot.com',
    iosClientId: '17338485793-ml19j0qcuhrq5vncqqsuh7r3abv2144d.apps.googleusercontent.com',
    iosBundleId: 'com.liklok.live.chat.liklok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjHPzLeAKPd4pyAxd0FeSiwsPjSoZybQ0',
    appId: '1:17338485793:ios:91fd85b193099a436ce760',
    messagingSenderId: '17338485793',
    projectId: 'liklok-88d38',
    storageBucket: 'liklok-88d38.appspot.com',
    iosClientId: '17338485793-ml19j0qcuhrq5vncqqsuh7r3abv2144d.apps.googleusercontent.com',
    iosBundleId: 'com.liklok.live.chat.liklok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfl7eZMCicJY8EPZzZNUp-27qmTtnovRU',
    appId: '1:17338485793:web:233e789da818ae176ce760',
    messagingSenderId: '17338485793',
    projectId: 'liklok-88d38',
    authDomain: 'liklok-88d38.firebaseapp.com',
    storageBucket: 'liklok-88d38.appspot.com',
    measurementId: 'G-T4QLT5P210',
  );

}