// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKLX3wO09ayV7W5vUELtIuhK6NMC4qscc',
    appId: '1:672957384118:web:58836e30b304ad6b6fed17',
    messagingSenderId: '672957384118',
    projectId: 'liklok-4286b',
    authDomain: 'liklok-4286b.firebaseapp.com',
    storageBucket: 'liklok-4286b.firebasestorage.app',
    measurementId: 'G-5Z2R5K3MT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_t_y5AjJEJW35CvQefNOdoKV5FZBU_iY',
    appId: '1:672957384118:android:d8c7a76bcb75e5276fed17',
    messagingSenderId: '672957384118',
    projectId: 'liklok-4286b',
    storageBucket: 'liklok-4286b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ePJjKNvoU2cRsWTCw12AtPHGrKlOyRo',
    appId: '1:672957384118:ios:9ea188c4e11098e36fed17',
    messagingSenderId: '672957384118',
    projectId: 'liklok-4286b',
    storageBucket: 'liklok-4286b.firebasestorage.app',
    iosClientId: '672957384118-v5ov3ls6mta264dhha6bhlier7kllm9i.apps.googleusercontent.com',
    iosBundleId: 'com.liklok.live.chat.liklok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ePJjKNvoU2cRsWTCw12AtPHGrKlOyRo',
    appId: '1:672957384118:ios:9ea188c4e11098e36fed17',
    messagingSenderId: '672957384118',
    projectId: 'liklok-4286b',
    storageBucket: 'liklok-4286b.firebasestorage.app',
    iosClientId: '672957384118-v5ov3ls6mta264dhha6bhlier7kllm9i.apps.googleusercontent.com',
    iosBundleId: 'com.liklok.live.chat.liklok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKLX3wO09ayV7W5vUELtIuhK6NMC4qscc',
    appId: '1:672957384118:web:5687954bce242d466fed17',
    messagingSenderId: '672957384118',
    projectId: 'liklok-4286b',
    authDomain: 'liklok-4286b.firebaseapp.com',
    storageBucket: 'liklok-4286b.firebasestorage.app',
    measurementId: 'G-TBK8EC1C0E',
  );

}