const Map<String, String> bn = {
  'about_us_title': 'অ্যাপের সম্পর্কে',
'about_us_version': 'সংস্করণ নম্বর',
'about_us_update_version': 'সংস্করণ আপডেট',
'about_us_official_website': 'আধিকারিক ওয়েবসাইট',
'account_management_title': 'অ্যাকাউন্ট ব্যবস্থাপনা',
'add_post': 'পোস্ট করুন',
'add_post_msg': 'আপনার পোস্টটি আমাদের একাধিক প্রশাসকের দ্বারা পর্যালোচনা করা হচ্ছে এবং শীঘ্রই অনুমোদিত হবে',
'add_photo_gallery': 'ছবির গ্যালারি',
'add_camera': 'ক্যামেরা',
'add_status_my_status': 'আমার অবস্থা',
'add_status_share': 'শেয়ার করুন',
'add_status_msg': 'অবস্থা সফলভাবে আপডেট হয়েছে',
'agreement_title': 'ব্যবহার চুক্তি',
'agreement_user_agreement': 'LikLok ব্যবহার চুক্তি',
'edit_language': 'ভাষা',
'edit_arabic': 'আরবি',
'edit_profile_title': 'প্রোফাইল সম্পাদনা',
'edit_profile_Cover_photo': 'কভারের ছবি',
'edit_profile_upload': 'আপলোড করুন',
'edit_profile_basic_information': 'মৌলিক তথ্য',
'edit_profile_user_name': 'ব্যবহারকারীর নাম',
'edit_profile_gender': 'লিঙ্গ',
'edit_profile_male': 'পুরুষ',
'edit_profile_female': 'মহিলা',
'edit_profile_date_of_birth': 'জন্ম তারিখ',
'edit_profile_country': 'দেশ',
'edit_profile_my_tags': 'আমার শখ',
'edit_profile_update': 'আপডেট করুন',
'edit_profile_tag_msg': 'আপনার শখ সফলভাবে আপডেট হয়েছে',
'edit_profile_user_name_title': 'ব্যবহারকারীর নাম',
'edit_profile_characters !': 'সর্বাধিক 20 অক্ষর !',
'edit_profile_enter_user_name': 'ব্যবহারকারীর নাম লিখুন',
'edit_profile_cancel': 'বাতিল করুন',
'edit_profile_edit': 'সম্পাদনা করুন',
'edit_profile_photo_msg': 'আপনার ছবি আপডেট হয়েছে!',
'edit_profile_Cover_msg': 'আপনার কভার আপডেট হয়েছে!',
'followers_title': 'অনুসরণকারী',
'following_title': 'অনুসরণ করা',
'friends_title': 'মিত্র',
'home_party': 'পার্টি',
'home_discover': 'আবিষ্কার',
'inner_report': 'রিপোর্ট',
'inner_block': 'ব্লক',
'inner_basic_information': 'মৌলিক তথ্য',
'inner_room_gifts': 'ঘরের উপহার',
'inner_my_frames': 'আমার ফ্রেম',
'inner_cars_(Entries)': 'গাড়ি (এন্ট্রি)',
'login_welcome_msg': 'LikLok এ স্বাগতম!',
'login_title': 'এটি মজা সম্পর্কে!',
'login_privacy': 'LikLok এ নিবন্ধনের মাধ্যমে আপনি একমত হচ্ছেন',
'login_policy': 'LikLok নীতি',
'login_and': 'এবং',
'login_services': 'LikLok ব্যবহার শর্ত',
'mall_title': 'দোকান',
'mall_purchase': 'ক্রয়',
'mall_msg': 'দুঃখিত আপনার কাছে পর্যাপ্ত সোনা নেই!',
'moments_recommend': 'প্রস্তাবিত',
'moments_mine': 'আমার পোস্ট',
'moments_follow': 'অনুসরণ করুন',
'moments_not_interested': 'আগ্রহী নয়',
'moments_report': 'রিপোর্ট',
'my_designs_days': 'দিন:',
'my_designs_use': 'ব্যবহার',
'my_level_wealth': 'অবদান',
'my_level_karizma': 'ক্যারিজমা',
'my_level_charging': 'চার্জিং',
'my_level_current_points': 'বর্তমান পয়েন্ট',
'my_level_next_level': 'পরবর্তী স্তরে',
'my_level_ways_to_level_up': 'স্তর বাড়ানোর উপায়?',
'my_level_send_gift': 'চ্যাট রুমে বন্ধুকে উপহার পাঠান',
'my_level_gold_point': '1 সোনা = 1 পয়েন্ট',
'my_level_receive': 'চ্যাট রুমে বন্ধুর থেকে উপহার গ্রহণ করুন',
'my_level_charge_your_gold': 'আপনার সোনা চার্জ করুন!',
'network_title': 'নেটওয়ার্ক ডায়াগনসিস',
'network_start': 'শুরু',
'notification_moments': 'মুহূর্ত',
'notification_profile': 'প্রোফাইল',
'notification_charging': 'চার্জিং',
'notification_system': 'সিস্টেম',
'notification_announcement': 'ঘোষণা',
'notification_setting_title': 'নোটিফিকেশন',
'notification_setting_private_chat': 'প্রাইভেট চ্যাট',
'notification_setting_new_followers': 'নতুন অনুসারীরা',
'notification_setting_invitation_message': 'আমন্ত্রণ বার্তা',
'notification_setting_moments_notification': 'মুহূর্তের নোটিফিকেশন',
'post_title': 'মুহূর্তের বিষয়বস্তু',
'post_label': 'দয়া করে বন্ধুত্বপূর্ণ হন!',
'post_msg': 'আপনার মন্তব্য সফলভাবে পাঠানো হয়েছে!',
'privacy_policy_title': 'গোপনীয়তা নীতি',
'privacy_policy': 'LikLok গোপনীয়তা নীতি',
'profile_msg_copied': 'আইডি নম্বর কপি হয়েছে!',
'profile_visitors': 'দর্শক',
'profile_gold': 'সোনা',
'profile_diamond': 'হীরক',
'profile_room': 'কক্ষ',
'profile_gifts': 'উপহার',
'profile_level': 'স্তর',
'profile_my_posts': 'আমার পোস্ট',
'profile_my_status': 'আমার অবস্থা',
'profile_invite_friends': 'বন্ধুদের আমন্ত্রণ জানান',
'profile_medals': 'মেডেল',
'profile_contact_us': 'আমাদের সাথে যোগাযোগ করুন',
'profile_terms_of_use': 'ব্যবহারের শর্ত',
'profile_account_settings': 'অ্যাকাউন্টের সেটিংস',
'search_user': 'ব্যবহারকারী',
'search_label_search': 'আইডি / নাম দ্বারা ব্যবহারকারীদের অনুসন্ধান করুন',
'setting_title': 'সেটিংস',
'setting_language': 'ভাষা',
'setting_notification': 'নোটিফিকেশন',
'setting_blocked_list': 'ব্লক তালিকা',
'setting_identity_verification': 'পরিচয় যাচাইকরণ',
'setting_clear_cache': 'ক্যাশ পরিষ্কার করুন',
'setting_views': 'দৃশ্য',
'taps_home': 'হোম',
'taps_chats': 'চ্যাট',
'taps_me': 'আমি',
'add_post_label': 'মুহূর্তের দেওয়ালে আপনার মতামত শেয়ার করুন!',
'gift_one_or_more_user': 'একজন বা তার বেশি ব্যবহারকারী',
'gift_all_mic_users': 'সব মাইক্রোফোন ব্যবহারকারী',
'gift_all_room_users': 'সব ঘর ব্যবহারকারী',
'gift_send_to_all_room_members': 'সব ঘরের সদস্যদের কাছে পাঠান',
'gift_send': 'পাঠান',
'menu_theme': 'পটভূমি',
'menu_music': 'সঙ্গীত',
'menu_lucky_number': 'লাকি নম্বর',
'menu_dice': 'জুয়া',
'menu_lucky_bag': 'লাকি ব্যাগ',
'menu_settings': 'সেটিংস',
'room_info_room_name': 'ঘরের নাম',
'room_info_room_admin': 'ঘরের প্রশাসক',
'room_info_room_country': 'ঘরের দেশ',
'room_settings': 'ঘরের সেটিংস',
'room_settings_room_title': 'ঘরের নাম',
'room_settings_update': 'আপডেট করুন',
'room_settings_hello': 'স্বাগতম বার্তা',
'room_settings_room_password': 'ঘরের পাসওয়ার্ড',
'room_settings_room_admins': 'ঘরের প্রশাসক',
'room_settings_room_block_list': 'ব্লক তালিকা',
'chats_massage': 'বার্তা',
'chats_friends': 'বন্ধুরা',
'chats_event_message': 'সক্রিয়তার নোটিফিকেশন',
'chats_club_chat_service': 'ক্লাব চ্যাট সেবা',
'chats_system_massage': 'সিস্টেম বার্তা',
'room_members': 'ঘরের সদস্যরা',
'log_out': 'লগ আউট',
'logout_msg': 'আপনি কি লগ আউট করতে চান?',
'delete_account': 'অ্যাকাউন্ট মুছে ফেলুন',
'delete_Account_msg': 'আপনি কি অ্যাকাউন্ট মুছে ফেলতে চান?',
'change_local': 'ভাষা পরিবর্তন',
'change_local_msg': 'আপনি কি অ্যাপ্লিকেশনের ভাষা পরিবর্তন করতে চান?',
'login_phone_title': 'আপনার মোবাইল নম্বর দিয়ে নিবন্ধন করুন',
'login_phone_hint': 'আপনার নম্বর দেশ কোড সহ লিখুন',
'send_btn': 'পাঠান',
"verify_btn": "নিশ্চিত করুন",
"verify_phone_hint": "সক্রিয়করণ কোড প্রবেশ করুন",
"verify_phone_title": "আপনার মোবাইল নম্বর সক্রিয় করুন",
"room_close_keep": "সংরক্ষণ",
"room_close_exit": "বহির্গমন",
'edit_ok': 'ঠিক আছে',
'add_status_label_text': '#আপনার জীবনী বন্ধুদের সাথে শেয়ার করুন!',
'invite_invite_friends': 'আপনার বন্ধুদের LikLok-এ আমন্ত্রণ জানান এবং একসাথে উদযাপন করুন!',
'invite_copy': 'আমন্ত্রণ লিংক কপি করুন',
'inner_msg_followed': 'আপনি এই ব্যবহারকারীকে অনুসরণ করেছেন',
'inner_msg_unfollowed': 'আপনি এই ব্যবহারকারীকে অনুসরণ বাতিল করেছেন',
'inner_msg_no_room': 'দুঃখিত, এই ব্যবহারকারীর কোনো ঘর নেই',
'inner_msg_not_any_room': 'দুঃখিত, এই ব্যবহারকারী কোনো ঘরে নেই',
'chat_search_friend': 'আপনার বন্ধুদের আইডি / নাম দ্বারা অনুসন্ধান করুন',
'remote_app_msg': 'আপনি এই ব্যবহারকারীকে রিপোর্ট করেছেন!',
'remote_app_msg_error ': 'ত্রুটি! কিছু ভুল হয়েছে',
'remote_app_msg_blocked': 'আপনি এই ব্যবহারকারীকে ব্লক করেছেন!',
'remote_chat_msg_failed': 'ঘর খুলতে ব্যর্থ হয়েছে, দয়া করে সহায়তার সাথে যোগাযোগ করুন',
'remote_design_msg_design': 'ডিজাইন ডিফল্ট মোডে সেট করুন',
'contact_Us_title': 'আমাদের সাথে যোগাযোগ করুন',
'contact_Us_club_chat': 'আমরা LikLok-এ আপনাকে সহায়তা করতে এবং আপনার অনুরোধগুলি পূরণ করতে খুশি, তাই কোনো সমস্যা হলে আমাদের সাথে যোগাযোগ করতে দ্বিধা করবেন না, আমরা ২৪ ঘণ্টা সারা সপ্তাহে আপনার সেবায় আছি',
'contact_Us_social_media': 'আমাদের সামাজিক মাধ্যমগুলিতে আপনাকে অনুসরণ করতে পেরে খুশি হব',
'verification_title': 'পরিচয় যাচাইকরণ',
'verification_id_card': 'আপনার পরিচয়পত্রের একটি ছবি সংযুক্ত করুন',
'verification_id_face': 'পরিচয়পত্রের মুখের ছবি',
'verification_id_back': 'পরিচয়পত্রের পেছনের ছবি',
'verification_verify': 'নিশ্চিত করুন',
'clear_cash_msg': 'ক্যাশ সফলভাবে মুছে ফেলা হয়েছে',
'chats_update_data_msg': 'সফলভাবে আপডেট হয়েছে',
'event_message_title': 'বার্তা সতর্কতা',
'customer_service_title': 'গ্রাহক সেবা',
'delete_chat': 'চ্যাট মুছুন',
'block_user': 'ব্লক',
'user_app_blocked_title': 'আপনাকে ব্লক করা হয়েছে!',
'user_app_blocked_msg': 'দুঃখিত, আপনি অ্যাপে প্রবেশ করতে পারবেন না কারণ আপনাকে অ্যাপের পরিষেবাগুলি ব্যবহারে ব্লক করা হয়েছে, আরও বিস্তারিত জানার জন্য প্রশাসনের সাথে যোগাযোগ করুন',
'recharge_gold': 'সোনার ক্রেডিট চার্জ করুন',
"diamond_exchange": "হীরার ক্রেডিট এক্সচেঞ্জ",
"diamond_exchange_inp_hint": "রূপান্তরের মূল্য লিখুন",
"diamond_exchange_note": "ন্যূনতম রূপান্তর মূল্য ১০০ হীরা",
"diamond_exchange_rules": "হীরা থেকে সোনায় রূপান্তরের নির্দেশিকা",
"wallet_diamond_rule1": "আপনার প্রাপ্ত উপহারগুলি স্বয়ংক্রিয়ভাবে নির্দিষ্ট এবং সম্মত শতাংশে হীরায় রূপান্তরিত হয়",
"wallet_diamond_rule2": "হীরার থেকে সোনায় রূপান্তরের হার হলো ",
"exchanged_gold": "রূপান্তরিত সোনার মূল্য: ",
"exchange_btn": "সোনায় রূপান্তর করুন",
"details": "বিস্তারিত",
"exchange_failed": "হীরা শুধুমাত্র ১০০ হীরার বা তার বেশি হলে রূপান্তর করা যেতে পারে",
"charging_details": "চার্জিংয়ের বিস্তারিত",
"exchange_failed2": "দুঃখিত, আপনার হীরার ক্রেডিট অনুমতি দেয় না",
"edit_profile_user_gender": "ব্যবহারকারীর প্রকার পরিবর্তন করুন",
"vip": "এরিস্টোক্রেটিক",
"vip_privileges": "এরিস্টোক্রেটিক সুবিধা",
"Vip_package": "এরিস্টোক্রেটিক প্যাকেজ",
"car": "গাড়ি",
"medal": "পদক",
"special_msg": "বিশেষ বার্তা",
"entering_effect": "প্রবেশের প্রভাব",
"login_time": "নিবন্ধনের তারিখ লুকান",
"stop_track": "ট্র্যাকিং বন্ধ করুন",
"no_kick": "ব্লক প্রতিরোধ করুন",
"use_mic": "মাইক ব্যবহার করুন",
"mic_closed_msg": "দুঃখিত, এই মাইক বন্ধ",
"un_use_mic": "মাইক থেকে বেরিয়ে আসুন",
"mute": "শব্দ নিভান",
"lock_mic": "মাইক বন্ধ করুন",
"lock_all_mics": "সব মাইক বন্ধ করুন",
"unlock_mic": "মাইক খুলুন",
"unlock_all_mic": "সব মাইক খুলুন",
'remove_from_mic': "মাইক থেকে সরান",
'chat_error': 'ত্রুটি',
'chat_loading': 'লোড হচ্ছে',
'inner_nothing': 'এখানে কিছুই নেই',
'inner_nothing_update': 'এখানে কিছুই নেই, আপনার জীবনী আপডেট করুন',
'login_verify_phone': 'দুঃখিত, আমরা এখন ফোনটি যাচাই করতে পারি না!',
'login_code_msg': 'যাচাইকরণ কোড সফলভাবে পাঠানো হয়েছে',
'network_msg': 'সব নেটওয়ার্ক পরিষেবা প্রত্যাশা অনুযায়ী কাজ করছে',
'splash_party': 'আপনার যতটা সম্ভব উদযাপন করুন',
'musics2_model_add_music': 'সঙ্গীত যোগ করুন',
'musics_model_my_music': 'আমার সঙ্গীত',
'agency_charge_title': 'সদস্যের ক্রেডিট চার্জ করুন',
'agency_charge_operation_title': 'চার্জিং অপারেশন',
'agency_charge_search': 'অনুসন্ধান',
'agency_charge_charge': 'চার্জ',
'agency_charge_user_data': 'ব্যবহারকারীর তথ্য',
'join_host_title': 'এজেন্সিতে যোগদানের আবেদন',
'join_host_request': 'যোগদানের আবেদন পাঠান',
'join_host_data': 'এজেন্সির তথ্য',
'agency_income_title': 'হোস্টের আয়',
'agency_income_target': 'লক্ষ্য',
'agency_income_work_hour': 'কাজের ঘণ্টার সংখ্যা',
'agency_income_hour': 'ঘণ্টা: ',
'agency_income_day': 'দিন: ',
'agency_income_work_points': 'বর্তমান পয়েন্টের সংখ্যা',
'agency_income_next_target': 'পরবর্তী লক্ষ্য অর্জনের জন্য বাকি',
'agency_income_next_achieve_target': 'পরবর্তী লক্ষ্য অর্জনের জন্য বাকি',
'block_msg_unblocked': 'আপনি এই ব্যবহারকারীকে আনব্লক করেছেন!',
'chat_hint_text_form': 'কিছু লিখুন ...',
'chat_no_resents': 'এখন কিছু নেই',
'room_close_mic': 'দুঃখিত, এই মাইক বন্ধ',
'room_msg': "LikLok পরিচালনা আপনাকে তাদের প্ল্যাটফর্মে মজাদার সময় কাটানোর আশা করে এবং সমস্ত সদস্যের মধ্যে যোগাযোগের শিষ্টাচার বজায় রাখতে এবং হয়রানি এড়াতে জোর দেয় এবং সংবেদনশীল, রাজনৈতিক এবং ধর্মীয় বিষয়গুলি লক্ষ্য করার জন্য সতর্ক করে",
"notice": "ঘরে প্রবেশ: ",
"user_enter_message": "হ্যালো ...",
"host_agency_search": "এজেন্সির আইডি দ্বারা অনুসন্ধান",
"request_process": "আপনার আবেদন বর্তমানে প্রক্রিয়াধীন",
"agency_members_title": "এজেন্সির সদস্য",
"choose_receiver": "প্রথমে উপহারের প্রাপক নির্বাচন করুন",
"choose_gift": "দয়া করে উপহার নির্বাচন করুন",
"daily": "দৈনিক",
"weekly": "সাপ্তাহিক",
"monthly": "মাসিক",
"app_rank": "LikLok র্যাংক",
"room_remove_mic": "দুঃখিত, প্রশাসক আপনাকে মাইক থেকে সরিয়ে দিয়েছে",
"music_error_permissions": "ফাইলের অনুমতি না দিলে সঙ্গীত ফাইলগুলি আপলোড করা সম্ভব নয়",
"unmute": "শব্দ চালু করুন",
"room_settings_room_subject": "ঘরের প্রকার",
"room_settings_room_img": "ঘরের ছবি",
"room_password_label": "ঘরের পাসওয়ার্ড",
"room_password_wrong": "ভুল পাসওয়ার্ড",
"show_profile": "ব্যবহারকারী দেখুন",
"admin_mic_alert": "দুঃখিত! এটি শুধুমাত্র প্রশাসকদের জন্য মাইক",
"should_be_on_mic": "দুঃখিত, আপনাকে মাইক ব্যবহারকারী হতে হবে!",
"add_admin": "অ্যাডমিন",
"add_admin_title": "ঘরের জন্য প্রশাসক যোগ করুন",
"admin_added": "নতুন প্রশাসক নিযুক্ত করা হয়েছে",
"remove_btn": "মুছুন",
"admin_deleted": "প্রশাসক মুছে ফেলা হয়েছে",
"room_save_dialog_title": "ঘরের সংরক্ষণ বাতিল করুন",
"room_save_dialog_msg": "আপনি কি ঘরের সংরক্ষণ বাতিল করতে চান",
"show_user": "ব্যবহারকারী দেখুন",
"counter_off": "গণনা বন্ধ",
"counter_on": "গণনা চালু",
"kick_out": "বহিষ্কার",
"kick_out_hour": "এক ঘন্টার জন্য বহিষ্কার",
"kick_out_day": "এক দিনের জন্য বহিষ্কার",
"kick_out_forever": "চিরকালীন বহিষ্কার",
"local_lucky_case": "স্থানীয় সৌভাগ্যের صندوق",
"global_lucky_case": "বিশ্বব্যাপী সৌভাগ্যের صندوق",
"benner_global_hint": "বিশ্বব্যাপী সৌভাগ্যের صندوق সমস্ত ঘরে প্রদর্শিত হবে",
"benner_global_hint2": "যে কেউ صندوق খুলতে এবং সোনালী পেতে পারে",
"benner_local_hint": "স্থানীয় সৌভাগ্যের صندوق ঘরের ভিতরে প্রদর্শিত হবে",
"lucky_case_msg": "আপনি সৌভাগ্যের صندوق থেকে পেয়েছেন ",
"rollet_value": "প্রবেশ ফি",
"rollet_max_members": "সর্বাধিক অংশগ্রহণকারী সংখ্যা",
"rollet_admin_play": "আমি ও অংশগ্রহণ করছি",
"rollet_start": "শুরু করুন",
"rollet_hint_text": "গেমটি শুরু করতে অন্তত দুইজন প্রয়োজন এবং গেমটি শুরু হলে অন্য কেউ যোগদান করতে পারবে না",
"rollet_join": "অংশগ্রহণ",
"no_active_rollet": "এখন কোন রোলেট নেই",
"kickout_msg": "আপনাকে প্রশাসক দ্বারা ঘর থেকে বহিষ্কার করা হয়েছে",
"room_blocked_msg": "দুঃখিত, আপনি বর্তমানে ঘরে প্রবেশ করতে পারবেন না",
"unblock_btn": "ব্লক বাতিল করুন",
"invite_link_copied": "অ্যাপের আমন্ত্রণ লিংক কপি করা হয়েছে",
"current_target": "বর্তমান লক্ষ্য",
"non": "(অব্যবহৃত)",
"next_target": "পরবর্তী লক্ষ্য",
"total_work_hours": "মোট কাজের ঘণ্টা",
"total_work_days": "মোট কাজের দিন",
"salary": "বর্তমান বেতন",
"check_privacy": "দয়া করে প্রথমে গোপনীয়তার নীতিতে সম্মত হন",
"no_data": "প্রদর্শনের জন্য কোন ডেটা নেই!",
"help_title": "সাহায্য কেন্দ্র",
"help_center_whatssapp": "হোয়াটসঅ্যাপে আপনার প্রশ্ন আমাদের জানান",
"help_center_website": "ভাল পরিষেবার জন্য আমাদের ওয়েবসাইটে যেতে পারেন",
"help_center_email": "অথবা আপনি ইমেইলের মাধ্যমে সহায়তা পেতে পারেন",
"read_more": "আরও পড়ুন",
"account_ban_title": "আপনার অ্যাকাউন্ট নিষিদ্ধ করা হয়েছে",
"account_ban_msg": "দুঃখিত, আপনার এই অ্যাকাউন্টের মাধ্যমে অ্যাপে প্রবেশ করা অনুমোদিত নয় কারণ এটি ব্যবহার শর্তাবলীর লঙ্ঘন হয়েছে",
"device_ban_title": "আপনার ফোন নিষিদ্ধ করা হয়েছে",
"device_ban_msg": "দুঃখিত, আপনার এই ফোনের মাধ্যমে অ্যাপে প্রবেশ করা অনুমোদিত নয় কারণ এটি ব্যবহার শর্তাবলীর লঙ্ঘন হয়েছে",
"charge_title": "চার্জ",
"get_8000_coins": "মাত্র ১ ডলারে ৮০০০ সোনালী ইউনিট পান",
"get_40000_coins": "মাত্র ৫ ডলারে ৪০০০০ সোনালী ইউনিট পান",
"get_160000_coins": "মাত্র ২০ ডলারে ১৬০০০০ সোনালী ইউনিট পান",
"get_400000_coins": "মাত্র ৫০ ডলারে ৪০০০০০ সোনালী ইউনিট পান",
"get_800000_coins": "মাত্র ১০০ ডলারে ৮০০০০০ সোনালী ইউনিট পান",
"new_joiner": "যোগদান গ্রহণ",
"kik_member": "সদস্যকে বহিষ্কার করুন",
"out_member": 'বহিষ্কৃত সদস্য',
"accept_member_title": "সদস্যের যোগদান গ্রহণ করুন",
"accept_member_msg": 'আপনি কি সদস্যের যোগদান গ্রহণ করতে চান',
"kik_member_title": "সদস্যকে বহিষ্কার করুন",
"kik_member_msg": "আপনি কি এই সদস্যকে বহিষ্কার করতে চান",
"moments": "মূহূর্তগুলি",
"chats": "বার্তা",
"me": "আমি",
"game1": "পাথর কাগজ কাঁচি",
"balance_added": "ব্যালেন্স সফলভাবে যুক্ত হয়েছে",
"agency_statics_title": "এজেন্সির পরিসংখ্যান",
"day_count": "দিনের সংখ্যা",
"point_count": "পয়েন্টের সংখ্যা",
"agent_salary": "এজেন্টের বেতন",
"host_agent": "হোস্টের বেতন",
  'indian_lang': 'হিন্দি ভাষা',
  'phlpini_lang': 'ফিলিপিনো ভাষা',
  'pangladish_lang': 'বাংলা ভাষা',
  'barazil_lang': 'ব্রাজিলিয়ান ভাষা (পর্তুগিজ)',
  'france_lang': 'ফরাসি',
  'games': 'গেমস',
  'chineese_lang':'চীনা ভাষা',
  'indonisian_lang':'ইন্দোনেশিয়ান',
  'relations': 'সম্পর্ক',
  'accept_btn': 'গ্রহণ',
  'cancel_btn': 'প্রত্যাখ্যান করতে',
  'relation_dialog_title':'বন্ধুর সাথে সম্পর্ক গ্রহণ বা প্রত্যাখ্যান করুন',
  'relation_dialog_msg': 'আপনার বন্ধুর পাঠানো সম্পর্ক গ্রহণ বা প্রত্যাখ্যান করুন',
  'Wallet_Charged_successfully': 'আপনার ওয়ালেট সফলভাবে চার্জ করা হয়েছে৷',
  'home_my_room': 'আমার',
  "create_room": 'শত্রিম নেই',
  'login_with_password': "নোবেল পাসওয়ার্ড লগইন",
  'login_with_password_disable': "পাসওয়ার্ড লগইন অক্ষম করুন",
  'change_password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'account_password': 'অ্যাকাউন্ট পাসওয়ার্ড',
  'enter_password': 'অ্যাকাউন্ট পাসওয়ার্ড লিখুন',
  're_enter_password': 'অ্যাকাউন্ট পাসওয়ার্ড পুনরায় লিখুন',
  'id_login': 'আইডি ব্যবহার করে লগইন করুন',
  'id_text': 'ID',
};