const Map<String, String> br = {
'about_us_title': 'Sobre o aplicativo',
'about_us_version': 'Número da versão',
'about_us_update_version': 'Atualizar versão',
'about_us_official_website': 'Site oficial',
'account_management_title': 'Gerenciamento de conta',
'add_post': 'Publicar',
'add_post_msg': 'Sua postagem está sendo revisada por um dos nossos moderadores e será aceita em breve',
'add_photo_gallery': 'Galeria de fotos',
'add_camera': 'Câmera',
'add_status_my_status': 'Meu status',
'add_status_share': 'Compartilhar',
'add_status_msg': 'Status atualizado com sucesso',
'agreement_title': 'Contrato de uso',
'agreement_user_agreement': 'Contrato de Uso do LikLok',
'edit_language': 'Idioma',
'edit_arabic': 'Árabe',
'edit_profile_title': 'Editar perfil',
'edit_profile_Cover_photo': 'Foto de capa',
'edit_profile_upload': 'Enviar',
'edit_profile_basic_information': 'Informações básicas',
'edit_profile_user_name': 'Nome de usuário',
'edit_profile_gender': 'Gênero',
'edit_profile_male': 'Masculino',
'edit_profile_female': 'Feminino',
'edit_profile_date_of_birth': 'Data de nascimento',
'edit_profile_country': 'País',
'edit_profile_my_tags': 'Meus hobbies',
'edit_profile_update': 'Atualizar',
'edit_profile_tag_msg': 'Seus hobbies foram atualizados com sucesso',
'edit_profile_user_name_title': 'Nome de usuário',
'edit_profile_characters !': 'Máximo de 20 caracteres!',
'edit_profile_enter_user_name': 'Digite o nome de usuário',
'edit_profile_cancel': 'Cancelar',
'edit_profile_edit': 'Editar',
'edit_profile_photo_msg': 'Sua foto foi atualizada!',
'edit_profile_Cover_msg': 'Sua capa foi atualizada!',
'followers_title': 'Seguidores',
'following_title': 'Seguindo',
'friends_title': 'Amigos',
'home_party': 'Festa',
'home_discover': 'Descobrir',
'inner_report': 'Relatório',
'inner_block': 'Bloquear',
'inner_basic_information': 'Informações básicas',
'inner_room_gifts': 'Presentes da sala',
'inner_my_frames': 'Meus quadros',
'inner_cars_(Entries)': 'Carros (Entradas)',
'login_welcome_msg': 'Bem-vindo ao LikLok!',
'login_title': 'É tudo sobre a diversão!',
'login_privacy': 'Ao se registrar no LikLok, você concorda com isso',
'login_policy': 'Política do LikLok',
'login_and': 'e',
'login_services': 'Termos de uso do LikLok',
'mall_title': 'Loja',
'mall_purchase': 'Comprar',
'mall_msg': 'Desculpe, você não tem ouro suficiente!',
'moments_recommend': 'Recomendado',
'moments_mine': 'Minhas postagens',
'moments_follow': 'Seguir',
'moments_not_interested': 'Não interessado',
'moments_report': 'Relatar',
'my_designs_days': 'Dias:',
'my_designs_use': 'Usar',
'my_level_wealth': 'Contribuição',
'my_level_karizma': 'Carisma',
'my_level_charging': 'Carregar',
'my_level_current_points': 'Pontos atuais',
'my_level_next_level': 'Para o próximo nível',
'my_level_ways_to_level_up': 'Como subir de nível?',
'my_level_send_gift': 'Envie um presente para um amigo na sala de chat',
'my_level_gold_point': '1 ouro = 1 ponto',
'my_level_receive': 'Receber um presente de um amigo na sala de chat',
'my_level_charge_your_gold': 'Carregue seu ouro!',
'network_title': 'Diagnóstico da rede',
'network_start': 'Iniciar',
'notification_moments': 'Momentos',
'notification_profile': 'Perfil',
'notification_charging': 'Carregando',
'notification_system': 'Sistema',
'notification_announcement': 'Anúncio',
'notification_setting_title': 'Notificações',
'notification_setting_private_chat': 'Chat privado',
'notification_setting_new_followers': 'Novos seguidores',
'notification_setting_invitation_message': 'Mensagem de convite',
'notification_setting_moments_notification': 'Notificação de momentos',
'post_title': 'Conteúdo do momento',
'post_label': 'Por favor, seja amigável!',
'post_msg': 'Seu comentário foi enviado com sucesso!',
'privacy_policy_title': 'Política de Privacidade',
'privacy_policy': 'Política de Privacidade do LikLok',
'profile_msg_copied': 'ID copiado!',
'profile_visitors': 'Visitantes',
'profile_gold': 'Ouro',
'profile_diamond': 'Diamante',
'profile_room': 'Sala',
'profile_gifts': 'Presentes',
'profile_level': 'Nível',
'profile_my_posts': 'Minhas postagens',
'profile_my_status': 'Meu status',
'profile_invite_friends': 'Convidar amigos',
'profile_medals': 'Medalhas',
'profile_contact_us': 'Contate-nos',
'profile_terms_of_use': 'Termos de uso',
'profile_account_settings': 'Configurações da conta',
'search_user': 'Usuário',
'search_label_search': 'Buscar usuários por ID / nome',
'setting_title': 'Configurações',
'setting_language': 'Idioma',
'setting_notification': 'Notificações',
'setting_blocked_list': 'Lista de bloqueados',
'setting_identity_verification': 'Verificação de identidade',
'setting_clear_cache': 'Limpar cache',
'setting_views': 'Visualizações',
'taps_home': 'Início',
'taps_chats': 'Chats',
'taps_me': 'Eu',
'add_post_label': 'Compartilhe sua opinião na parede dos momentos!',
'gift_one_or_more_user': 'Um usuário ou mais',
'gift_all_mic_users': 'Todos os usuários do microfone',
'gift_all_room_users': 'Todos os usuários da sala',
'gift_send_to_all_room_members': 'Enviar para todos os membros da sala',
'gift_send': 'Enviar',
'menu_theme': 'Fundos',
'menu_music': 'Música',
'menu_lucky_number': 'Número da sorte',
'menu_dice': 'Dados',
'menu_lucky_bag': 'Saco da sorte',
'menu_settings': 'Configurações',
'room_info_room_name': 'Nome da sala',
'room_info_room_admin': 'Administrador da sala',
'room_info_room_country': 'País da sala',
'room_settings': 'Configurações da sala',
'room_settings_room_title': 'Nome da sala',
'room_settings_update': 'Atualizar',
'room_settings_hello': 'Mensagem de boas-vindas',
'room_settings_room_password': 'Senha da sala',
'room_settings_room_admins': 'Administradores da sala',
'room_settings_room_block_list': 'Lista de bloqueados',
'chats_massage': 'Mensagens',
'chats_friends': 'Amigos',
'chats_event_message': 'Notificações de atividades',
'chats_club_chat_service': 'Serviço ao cliente',
'chats_system_massage': 'Mensagens do sistema',
'room_members': 'Membros da sala',
'log_out': 'Sair',
'logout_msg': 'Deseja sair?',
'delete_account': 'Excluir conta',
'delete_Account_msg': 'Deseja excluir a conta?',
'change_local': 'Mudar idioma',
'change_local_msg': 'Deseja mudar o idioma do aplicativo?',
'login_phone_title': 'Cadastre-se com seu número de celular',
'login_phone_hint': 'Digite seu número com o código do país',
'send_btn': 'Enviar',
'verify_btn': 'Confirmar',
'verify_phone_hint': 'Insira o código de ativação',
'verify_phone_title': 'Ative seu número de celular',
'room_close_keep': 'Salvar',
'room_close_exit': 'Sair',
'edit_ok': 'OK',
'add_status_label_text': '#Compartilhe sua biografia com amigos!',
'invite_invite_friends': 'Convide seus amigos para o LikLok e celebre juntos!',
'invite_copy': 'Copiar link de convite',
'inner_msg_followed': 'Você seguiu este usuário',
'inner_msg_unfollowed': 'Você deixou de seguir este usuário',
'inner_msg_no_room': 'Desculpe, este usuário não tem uma sala',
'inner_msg_not_any_room': 'Desculpe, este usuário não está em nenhuma sala',
'chat_search_friend': 'Busque seus amigos pelo ID / nome',
'remote_app_msg': 'Você denunciou este usuário!',
'remote_app_msg_error': 'Erro! Ocorreu um erro',
'remote_app_msg_blocked': 'Você bloqueou este usuário!',
'remote_chat_msg_failed': 'Falha ao abrir a sala, entre em contato com o suporte',
'remote_design_msg_design': 'Definir design para o padrão',
'contact_Us_title': 'Entre em contato conosco',
'contact_Us_club_chat': 'Estamos felizes em ajudar e atender seus pedidos para tornar sua experiência no aplicativo agradável. Não hesite em nos contatar se tiver algum problema. Estamos sempre à sua disposição 24 horas por dia, 7 dias por semana.',
'contact_Us_social_media': 'Ficaremos felizes em segui-lo em nossas redes sociais',
'verification_title': 'Verificação de identidade',
'verification_id_card': 'Por favor, anexe uma foto do seu documento de identidade',
'verification_id_face': 'Foto do rosto com o documento de identidade',
'verification_id_back': 'Foto do verso do documento de identidade',
'verification_verify': 'Confirmar',
'clear_cash_msg': 'Cache excluído com sucesso',
'chats_update_data_msg': 'Atualizado com sucesso',
'event_message_title': 'Mensagens de alerta',
'customer_service_title': 'Serviço ao cliente',
'delete_chat': 'Excluir conversa',
'block_user': 'Bloquear',
'user_app_blocked_title': 'Você foi bloqueado!',
'user_app_blocked_msg': 'Desculpe, você não pode acessar o aplicativo, pois foi bloqueado de usar os serviços. Você pode entrar em contato com a administração para mais detalhes.',
'recharge_gold': 'Recarregar saldo de ouro',
'diamond_exchange': 'Trocar saldo de diamante',
'diamond_exchange_inp_hint': 'Digite o valor da troca',
'diamond_exchange_note': 'O valor mínimo para troca é 100 diamantes',
'diamond_exchange_rules': 'Instruções para trocar diamantes por ouro',
'wallet_diamond_rule1': 'Os presentes que você recebe são automaticamente convertidos em diamantes na proporção acordada',
'wallet_diamond_rule2': 'A proporção de conversão de diamantes em ouro é',
'exchanged_gold': 'Valor do ouro convertido:',
'exchange_btn': 'Converter para ouro',
'details': 'Detalhes',
'exchange_failed': 'Não é possível converter diamantes a menos que o valor seja 100 diamantes ou mais',
'charging_details': 'Detalhes de recarga',
'exchange_failed2': 'Desculpe, seu saldo de diamantes não é suficiente',
'edit_profile_user_gender': 'Editar gênero do usuário',
'vip': 'VIP',
'vip_privileges': 'Privilégios VIP',
'Vip_package': 'Pacote VIP',
'car': 'Carro',
'medal': 'Medalha',
'special_msg': 'Mensagens especiais',
'entering_effect': 'Efeito de entrada',
'login_time': 'Ocultar data de registro',
'stop_track': 'Parar rastreamento',
'no_kick': 'Impedir expulsão',
'use_mic': 'Subir no microfone',
'mic_closed_msg': 'Desculpe, este microfone está fechado',
'un_use_mic': 'Sair do microfone',
'mute': 'Silenciar',
'lock_mic': 'Trancar microfone',
'lock_all_mics': 'Trancar todos os microfones',
"unlock_mic": "Desbloquear o microfone",
"unlock_all_mic": "Desbloquear todos os microfones",
'remove_from_mic': "Remover do microfone",
'chat_error': 'Erro',
'chat_loading': 'Carregando',
'inner_nothing': 'Nada aqui',
'inner_nothing_update': 'Nada aqui, atualize seu perfil',
'login_verify_phone': 'Desculpe, não conseguimos verificar o telefone agora!',
'login_code_msg': 'Código de verificação enviado com sucesso',
'network_msg': 'Todos os serviços de rede estão funcionando como esperado',
'splash_party': 'Celebre sempre que puder',
'musics2_model_add_music': 'Adicionar música',
'musics_model_my_music': 'A música',
'agency_charge_title': 'Recarregar saldo do membro',
'agency_charge_operation_title': 'Operações de recarga',
'agency_charge_search': 'Pesquisar',
'agency_charge_charge': 'Recarregar',
'agency_charge_user_data': 'Dados do usuário',
'join_host_title': 'Solicitar adesão à agência',
'join_host_request': 'Enviar solicitação de adesão',
'join_host_data': 'Dados da agência',
'agency_income_title': 'Renda do anfitrião',
'agency_income_target': 'Objetivo',
'agency_income_work_hour': 'Número de horas de trabalho',
'agency_income_hour': 'Hora: ',
'agency_income_day': 'Dia: ',
'agency_income_work_points': 'Número de pontos atuais',
'agency_income_next_target': 'Faltam para atingir o próximo objetivo.',
'agency_income_next_achieve_target': 'Faltam para atingir o próximo objetivo',
'block_msg_unblocked': 'Você desbloqueou este usuário!',
'chat_hint_text_form': 'Escreva algo...',
'chat_no_resents': 'Nada no momento',
'room_close_mic': 'Desculpe, este microfone está fechado',
'room_msg': "A administração do LikLok deseja que você tenha um bom tempo em sua plataforma e enfatiza a importância de manter a etiqueta de comunicação entre todos os membros, evitando assédio e alertando sobre a abordagem de temas sensíveis, políticos e religiosos.",
"notice": "Entrada na sala: ",
"user_enter_message": "Olá...",
"host_agency_search": "Pesquisar pelo ID da agência",
"request_process": "Sua solicitação está sendo processada",
"agency_members_title": "Membros da agência",
"choose_receiver": "Você deve selecionar um destinatário para o presente primeiro",
"choose_gift": "Por favor, escolha o presente",
"daily": "Diário",
"weekly": "Semanal",
"monthly": "Mensal",
"app_rank": "Ranking do LikLok",
"room_remove_mic": "Desculpe, você foi removido do microfone pelo administrador",
"music_error_permissions": "Não é possível carregar arquivos de música sem conceder permissão de acesso aos arquivos",
"unmute": "Ativar som",
"room_settings_room_subject": "Tipo de sala",
"room_settings_room_img": "Imagem da sala",
"room_password_label": "Senha da sala",
"room_password_wrong": "Senha incorreta",
"show_profile": "Ver usuário",
"admin_mic_alert": "Desculpe! Microfone reservado apenas para administradores",
"should_be_on_mic": "Desculpe, você deve ser um usuário de microfone!",
"add_admin": "Adicionar administrador",
"add_admin_title": "Adicionar administrador à sala",
"admin_added": "Novo administrador atribuído",
"remove_btn": "Excluir",
"admin_deleted": "Administrador excluído",
"room_save_dialog_title": "Cancelar a retenção da sala",
"room_save_dialog_msg": "Você deseja cancelar a retenção da sala?",
"show_user": "Ver usuário",
"counter_off": "Contador desativado",
"counter_on": "Contador ativado",
"kick_out": "Expulsar",
"kick_out_hour": "Expulsar por uma hora",
"kick_out_day": "Expulsar por um dia",
"kick_out_forever": "Expulsar permanentemente",
"local_lucky_case": "Caixa da sorte local",
"global_lucky_case": "Caixa da sorte global",
"benner_global_hint": "A caixa da sorte global será exibida em todas as salas",
"benner_global_hint2": "Qualquer pessoa pode abrir a caixa e obter ouro",
"benner_local_hint": "A caixa da sorte local será exibida dentro da sala",
"lucky_case_msg": "Você ganhou da caixa da sorte ",
"rollet_value": "Taxa de entrada",
"rollet_max_members": "Número máximo de participantes",
"rollet_admin_play": "Eu também participo",
"rollet_start": "Começar",
"rollet_hint_text": "É necessário pelo menos duas pessoas para iniciar o jogo e os outros não podem entrar após o início do jogo",
"rollet_join": "Participar",
"no_active_rollet": "Não há roleta no momento",
"kickout_msg": "Você foi expulso da sala pelo administrador",
"room_blocked_msg": "Desculpe, você não pode entrar na sala no momento",
"unblock_btn": "Cancelar bloqueio",
"invite_link_copied": "Link de convite do aplicativo copiado",
"current_target": "Objetivo atual",
"non": "(Não definido)",
"next_target": "Próximo objetivo",
"total_work_hours": "Total de horas trabalhadas",
"total_work_days": "Total de dias trabalhados",
"salary": "Salário atual",
"check_privacy": "Por favor, aceite a política de privacidade primeiro",
"no_data": "Não há dados para exibir!",
"help_title": "Central de Ajuda",
"help_center_whatssapp": "Compartilhe sua dúvida pelo WhatsApp",
"help_center_website": "Você pode visitar nosso site para melhor atendimento",
"help_center_email": "Ou você pode obter suporte por e-mail",
"read_more": "Leia mais",
"account_ban_title": "Sua conta foi bloqueada",
"account_ban_msg": "Desculpe, você não pode acessar o aplicativo com esta conta, pois sua conta foi bloqueada por violar os termos de uso",
"device_ban_title": "Seu dispositivo foi bloqueado",
"device_ban_msg": "Desculpe, você não pode acessar o aplicativo com este telefone, pois seu dispositivo foi bloqueado por violar os termos de uso",
"charge_title": "Recarga",
"get_8000_coins": "Obtenha 8000 unidades de ouro por apenas 1 dólar",
"get_40000_coins": "Obtenha 40000 unidades de ouro por apenas 5 dólares",
"get_160000_coins": "Obtenha 160000 unidades de ouro por apenas 20 dólares",
"get_400000_coins": "Obtenha 400000 unidades de ouro por apenas 50 dólares",
"get_800000_coins": "Obtenha 800000 unidades de ouro por apenas 100 dólares",
"new_joiner": "Aceitar adesão",
"kik_member": "Expulsar membro",
"out_member": "Membro expulso",
"accept_member_title": "Aceitar adesão de membro",
"accept_member_msg": "Você deseja aceitar a adesão do membro?",
"kik_member_title": "Expulsar membro",
"kik_member_msg": "Você deseja expulsar este membro?",
"moments": "Momentos",
"chats": "Mensagens",
"me": "Eu",
"game1": "Pedra Papel Tesoura",
"balance_added": "Saldo adicionado com sucesso",
"agency_statics_title": "Estatísticas da agência",
"day_count": "Número de dias",
"point_count": "Número de pontos",
"agent_salary": "Salário do agente",
"host_agent": "Salário do anfitrião",
  'indian_lang': 'Língua hindi',
  'phlpini_lang': 'Língua filipina',
  'pangladish_lang': 'Língua bengali',
  'barazil_lang': 'Língua brasileira (português)',
  'france_lang': 'Francês',
  'games': 'Jogos',
  'chineese_lang':'Língua chinesa',
  'indonisian_lang':'indonésio',
  'relations': 'relações'



};