const Map<String,String> en ={
  'about_us_title' : 'About Us',
  'about_us_version' : 'Version',
  'about_us_update_version' : 'Update Version',
  'about_us_official_website' : 'Official Website',
  'account_management_title' : 'Account Management',
  'add_post' : 'Post',
  'add_post_msg' : 'Your post is being reviewed by one of our admins and it will be accepted very soon',
  'add_photo_gallery' : 'Photo Gallery',
  'add_camera' : 'Camera',
  'add_status_my_status' : 'My Status',
  'add_status_share' : 'Share',
  'add_status_msg' : 'Status Updated Successfully',
  'agreement_title' : 'Agreement',
  'agreement_user_agreement' : 'LikLok User Agreement',
  'edit_language' : 'Edit Language',
  'edit_arabic' : 'Arabic',
  'edit_profile_title' : 'Edit Profile',
  'edit_profile_Cover_photo' : 'Cover Photo',
  'edit_profile_upload' : 'Upload',
  'edit_profile_basic_information' : 'Basic Information',
  'edit_profile_user_name' : 'User Name',
  'edit_profile_gender' : 'Gender',
  'edit_profile_male' : 'Male',
  'edit_profile_female' : 'Female',
  'edit_profile_date_of_birth' : 'Date of Birth',
  'edit_profile_country' : 'Country',
  'edit_profile_my_tags' : 'My Tags',
  'edit_profile_update' : 'Update',
  'edit_profile_tag_msg' : 'Tags Updated Successfully',
  'edit_profile_user_name_title' : 'User Name',
  'edit_profile_characters !' : 'Up to 20 Characters !',
  'edit_profile_enter_user_name' : 'Enter User Name',
  'edit_profile_cancel' : 'CANCEL',
  'edit_profile_edit' : 'Edit',
  'edit_profile_photo_msg' : 'Your photo has been updated!',
  'edit_profile_Cover_msg' : 'Your Cover has been updated!',
  'followers_title' : 'Followers',
  'following_title' : 'Following',
  'friends_title' : 'Friends',
  'home_party' : 'Party',
  'home_discover' : 'Discover',
  'inner_report' : 'Report',
  'inner_block' : 'Block',
  'inner_basic_information' : 'Basic Information',
  'inner_room_gifts' : 'Room Gifts',
  'inner_my_frames' : 'My Frames',
  'inner_cars_(Entries)' : 'Cars (Entries)',
  'login_welcome_msg' : 'Welcome To LikLok !',
  'login_title' : 'Welcome To LikLok !',
  'login_privacy' : 'By signing in LikLok you agree to',
  'login_policy' : 'LikLok Policy',
  'login_and' : 'and',
  'login_services' : 'LikLok Terms Services',
  'mall_title' : 'Mall',
  'mall_purchase' : 'Purchase',
  'mall_msg' : 'Sorry you do not have enough gold !',
  'moments_recommend':'Recommend',
  'moments_mine':'Mine',
  'moments_follow':'Follow',
  'moments_not_interested':'Not Interested',
  'moments_report':'report',
  'my_designs_days':'Days:',
  'my_designs_use':'Use',
  'my_level_wealth':'Wealth',
  'my_level_karizma':'Karizma',
  'my_level_charging':'Charging',
  'my_level_current_points':'The Current Points',
  'my_level_next_level':'To The Next Level',
  'my_level_ways_to_level_up':'Ways To Level Up ?',
  'my_level_send_gift':'Send Gift to friend in Chat Room',
  'my_level_gold_point':'1 Gold = 1 Point',
  'my_level_receive':'Receive Gift to Friend in Chat Room',
  'my_level_charge_your_gold':'Charge Your Gold !',
  'network_title':'Network Diagnosis',
  'network_start':'Start',
  'notification_moments':'Moments',
  'notification_profile':'Profile',
  'notification_charging':'Charging',
  'notification_system':'System',
  'notification_announcement':'Announcement',
  'notification_setting_title':'Notification',
  'notification_setting_private_chat':'Private Chat',
  'notification_setting_new_followers':'New followers',
  'notification_setting_invitation_message':'Invitation Message',
  'notification_setting_moments_notification':'Moments Notification',
  'post_title':'Moment Content',
  'post_label':'Please be Friendly !',
  'post_msg':'Your comment Sent Successfully!',
  'privacy_policy_title':'Privacy Policy',
  'privacy_policy':'LikLok Privacy Policy',
  'profile_msg_copied':'User ID Copied !',
  'profile_visitors':'Visitors',
  'profile_gold':'Gold',
  'profile_diamond':'Diamond',
  'profile_room':'Room',
  'profile_gifts':'Gifts',
  'profile_level':'Level',
  'profile_my_posts':'My Posts',
  'profile_my_status':'My Status',
  'profile_invite_friends':'Invite Friends',
  'profile_medals':'Medals',
  'profile_contact_us':'Contact Us',
  'profile_terms_of_use':'Terms of Use',
  'profile_account_settings':'Account Settings',
  'search_user':'User',
  'search_label_search':'Search in Users by ID / Name',
  'setting_title':'Setting',
  'setting_language':'Language',
  'setting_notification':'Notification',
  'setting_blocked_list':'Blocked List',
  'setting_identity_verification':'Identity Verification',
  'setting_clear_cache':'Clear Cache',
  'setting_views':'Views',
  'taps_home':'Home',
  'taps_chats':'Chats',
  'taps_me':'Me',
  'add_post_label':'Share Your Thoughts on Moments wall !',
  'gift_one_or_more_user':'select user',
  'gift_all_mic_users':'All Mic Users',
  'gift_all_room_users':'All Room Users',
  'gift_send_to_all_room_members':'Send to All Room Members',
  'gift_send':'Send',
  'menu_theme':'Theme',
  'menu_music':'Music',
  'menu_lucky_number':'Lucky Number',
  'menu_dice':'Dice',
  'menu_lucky_bag':'Lucky Box',
  'menu_settings':'Settings',
  'room_info_room_name':'Room Name',
  'room_info_room_admin':'Room Admin',
  'room_info_room_country':'Room Country',
  'room_settings':'Room Settings',
  'room_settings_room_title':'Room Title',
  'room_settings_update':'update',
  'room_settings_hello':'Room Hello Text',
  'room_settings_room_password':'Room Password',
  'room_settings_room_admins':'Room Admins',
  'room_settings_room_block_list':'Room Block List',
  'chats_massage':'Massage',
  'chats_friends':'Friends',
  'chats_event_message':'Event Message',
  'chats_club_chat_service':'Customer Service',
  'chats_system_massage':'System Message',
  'room_members': 'Room Members',
   'log_out': "LogOut",
  "logout_msg": "Do You really want to LogOut ?",
  "delete_account":"Delete Account",
  "delete_Account_msg":"Do You really want to Delete Account ?",
  "change_local": " Change Language",
  "change_local_msg": "Do You really want to Change App Language ?",
  "login_phone_title": "Login With Your Phone Number",
  'login_phone_hint': "Enter Phone Number With Country Code",
  "send_btn": "Send",
  "verify_btn":"Verify",
  "verify_phone_hint": "Enter Verification Code ",
  "verify_phone_title": "Verify Phone Number",
  "room_close_keep": "Keep",
  "room_close_exit": "Exit",
  'edit_ok' : 'OK',
  'add_status_label_text' : '#Share Your Bio With Friends!',
  'invite_invite_friends' : 'Invite Your Friends to LikLok and party together!',
  'invite_copy' : 'Copy the invitation link ',
  'inner_msg_followed' : 'you have followed this user',
  'inner_msg_unfollowed' : 'you have unfollowed this user',
  'inner_msg_no_room' : 'Sorry this user has no room',
  'inner_msg_not_any_room' : 'Sorry this user has no room',
  'chat_search_friend' : 'Search in Your Friend by ID / Name',
  'remote_app_msg' : 'You have reported this user !',
  'remote_app_msg_error' : 'Error! Something went wrong',
  'remote_app_msg_blocked' : 'You have blocked this user !',
  'remote_chat_msg_failed' : 'Failed to open room , please contact support',
  'remote_design_msg_design' : 'Design set to default',
  'contact_Us_title' : 'Contact Us',
  'contact_Us_club_chat' : 'We at LikLok are happy to help you, fulfill your requests and make your experience of using the application a fun experience, so do not delay in contacting us if you face any problem, we are always at your service 24 hours a day, 7 days a week ',
  'contact_Us_social_media' : 'We will also be happy to follow you on social media platforms',
  'verification_title' : 'Verification',
  'verification_id_card' : 'Please attach a copy of your ID card',
  'verification_id_face' : 'A photo of the face of the ID card',
  'verification_id_back' : 'A photo of the back of the ID card',
  'verification_verify' : 'Verify',
  'clear_cash_msg': 'Cash Cleared Successfully',
  'chats_update_data_msg' : 'Data Update Successfully',
  'event_message_title' : 'Event Message',
  'customer_service_title' : 'Customer Service',
  'delete_chat' : 'Delete Chat',
  'block_user' : 'Block User',
  'user_app_blocked_title': "You are Blocked !",
  "user_app_blocked_msg":"Sorry you can not enter the app as you are blocked from using our app services , please contact support for further actions ",
  "recharge_gold": "Recharge Gold Balance",
  "diamond_exchange": "Diamond Exchange",
  "diamond_exchange_inp_hint": "Enter Exchange Value",
  "diamond_exchange_note": "* At least exchange of 100 diamonds",
  "diamond_exchange_rules": "Diamond Exchange Rules",
  "wallet_diamond_rule1": "The gifts you receive will be automatically converted into diamonds",
  "wallet_diamond_rule2": "the ratio of diamond to golds is ",
  "exchanged_gold": "The Exchanged Gold: ",
  "exchange_btn": "Exchange To Gold",
  "details": "Details",
  "exchange_failed": "At least exchange of 100 diamonds",
  "charging_details": "Charging Details",
  "exchange_failed2": "No Balance !",
  "edit_profile_user_gender": "Edit User Gender",
  "vip": "VIP",
  "vip_privileges": "vip privileges",
  "Vip_package": "Vip Package",
  "car": "Car",
  "medal": "Medal",
  "special_msg": "Special Messages",
  "entering_effect": "Entering effects",
  "login_time":"Hide First Login",
  "stop_track": "No Track",
  "no_kick": "No Kick out",
  "use_mic": "Use Mic",
  "mic_closed_msg": "Sorry this mic is closed !",
  "un_use_mic": "Leave Mic  ",
  "mute": "Mute Mic",
  "lock_mic": "Lock Mic",
  "lock_all_mics": "Lock All Mics ",
  "unlock_mic": "unLock Mic",
  "unlock_all_mic": "unLock All Mics",
  'remove_from_mic': "Remove From Mic ",
  'chat_error': 'Error',
  'chat_loading': 'Loading',
  'inner_nothing': 'Nothing here',
  'inner_nothing_update': 'Nothing here , update your bio',
  'login_verify_phone': 'sorry we can not verify phone right now !',
  'login_code_msg': 'code sent successfully',
  'network_msg': 'All Network Services is working as expected',
  'splash_party':'Party whenever you can',
  'musics2_model_add_music': 'Add Music',
  'musics_model_my_music':'My Music',
  'agency_charge_title':'Agency Charge',
  'agency_charge_operation_title' : 'Agency Charge Operation',
  'agency_charge_search' : 'Search',
  'agency_charge_charge' : 'Charge',
  'agency_charge_user_data' : 'User Data',
  'join_host_title' : 'Request to join the Agency',
  'join_host_request' : 'Send Join Request',
  'join_host_data' : 'Agency Data',
  'agency_income_title' : 'Agency Income',
  'agency_income_target' : 'Target',
  'agency_income_work_hour' : 'Number of work hour',
  'agency_income_hour' : 'Hour : ',
  'agency_income_day' : 'Day : ',
  'agency_income_work_points' : 'Number of current points',
  'agency_income_next_target' : 'Remain To Achieve Next Target',
  'agency_income_next_achieve_target' : 'Remain To Achieve Next Target',
  'block_msg_unblocked' : 'You have unblocked this user !',
  'chat_hint_text_form' : 'Enter Something...',
  'chat_no_resents' : 'No Resents',
  'room_close_mic' : 'sorry this mic is close',
  'room_msg': 'LikLok management wishes you to spend enjoyable times on its platform and stresses the importance of maintaining communication etiquette among all members and avoiding harassment, and warns against targeting sensitive, political and religious topics.',
  "notice": "Room Entery :",
  "user_enter_message": "Welcome ...",
  "host_agency_search": "Search By Agency ID",
  "request_process":"your request is being processed",
  "agency_members_title" : "Agency Members",
  "choose_receiver": "Please select receiver first !",
  "choose_gift": "Please select a Gift first !",
  "daily": "Daily",
  "weekly":"Weekly",
  "monthly":"Monthly",
  "app_rank": "LikLok Rank",
  "room_remove_mic": "Sorry the admin remove you from mic !",
  "music_error_permissions": "ٍMusic Files Can not be loaded without this permission!",
  "unmute": "Un Mute",
  "room_settings_room_subject": "Room Category",
  "room_settings_room_img": "Room Image",
  "room_password_label": "Room Password",
  "room_password_wrong": "Incorrect Room Password!",
  "show_profile": "Show Profile",
  "admin_mic_alert": "This Mic is for Admins Only",
  "should_be_on_mic": "Sorry! you should be on mic",
  "add_admin": "Admin",
  "add_admin_title": "Add Room Admin",
  "admin_added": "New Admin Added Successfully",
  "remove_btn": "Remove",
  "admin_deleted": "Admin Deleted Successfully",
  "room_save_dialog_title": "End Room Save",
  "room_save_dialog_msg": "Do you need to end Room Keeping ?",
  "show_user":"Show Profile",
  "counter_off":"counter OFF",
  "counter_on":"Counter ON",
   "kick_out": "Kick Out",
  "kick_out_hour": "Block for an Hour",
  "kick_out_day": "Block for a Day",
  "kick_out_forever": "Block for ever`",
  "local_lucky_case": "Local Lucky Box",
  "global_lucky_case": "Global Lucky Box",
  "benner_global_hint": "Global Box will be displayed in all Rooms",
  "benner_global_hint2": "anyone can open the Box and get gold",
  "benner_local_hint": "Local Box will be displayed in The Room",
  "lucky_case_msg": "Yoi got from the Lucky Box ",
  "rollet_value": "Entry Fee",
  "rollet_max_members": "Max players",
  "rollet_admin_play": "I'm also participating",
  "rollet_start": "Start",
  "rollet_hint_text": 'It takes at least two people to start the game and others cannot join after the game has started',
  "rollet_join": "Join",
  "no_active_rollet": "There is no active Roulette now",
  "kickout_msg": " You were kicked out of the room by the admin  ",
  "room_blocked_msg": "Sorry, you cannot enter the room at the moment",
  "unblock_btn": "UnBlock",
  "invite_link_copied": "Invitation Link Copied!",
  "current_target": "Current Target",
  "non": "(NON)",
  "next_target": "Next Target",
  "total_work_hours": "Total Work Hours",
  "total_work_days":"Total Work Days",
  "salary": "Current Salary",
  "check_privacy": "Please confirm reading the app policy first!",
  "no_data" : "Sorry! there is no data to Load !",
  "help_title": "Help Center",
  "help_center_whatssapp": "Share your inquiries on whatsapp ",
  "help_center_website": "You can visit our website for better service",
  "help_center_email" : "Or you can receive support through email",
  "read_more" : "Read More",
  "account_ban_title": "Your account has been blocked",
  "account_ban_msg": "Sorry, you cannot be allowed to access the application using this account, as your account has been blocked for violating the terms of use",

  "device_ban_title": "Your mobile has been blocked",
  "device_ban_msg": "Sorry, you cannot be allowed to access the application using this mobile, as your mobile has been blocked for violating the terms of use",
  "charge_title": "Recharge",
  "get_8000_coins": "Get 8000 gold unit for only 1 dollar",
  "get_40000_coins": "Get 40000 gold unit for only 5 dollar",
  "get_160000_coins": "Get 160000 gold unit for only 20 dollar",
  "get_400000_coins": "Get 400000 gold unit for only 50 dollar",
  "get_800000_coins": "Get 800000 gold unit for only 100 dollar",
  "new_joiner": "Accept",
  "kik_member": "Kick out",
  "out_member": 'Kicked Out',
  "accept_member_title": "Accept Member",
  "accept_member_msg": 'Do you Really need to accept this new join request',
  "kik_member_title":"kick Out Member",
  "kik_member_msg": "Do you Really need to Kik out this member",
  "moments": "Moments",
  "chats": "Messages",
  "me": "Me",
  "game1": "rock-paper-scissors",
  "balance_added": "Balance Added Successfully!",
  "agency_statics_title": "Agency Statics",
  "day_count": "Days Count",
  "point_count": "Points Count",
  "agent_salary":"Agent Salary",
  "host_agent": "Host Salary",
  'indian_lang': 'Hindi language',
  'phlpini_lang': 'Filipino language',
  'pangladish_lang': 'Bengali language',
  'barazil_lang': 'Brazilian (Portuguese)',
  'france_lang': 'French',
  'games': 'Games',
  'chineese_lang':'Chinese language',
  'indonisian_lang':'Indonesian',
  'relations': 'Relations',
  'accept_btn': 'Accept',
  'cancel_btn': 'Reject',
  'relation_dialog_title':'Accept or reject a relationship with a friend',
  'relation_dialog_msg': 'Please accept or reject the relationship sent by your friend.',
  'Wallet_Charged_successfully': 'Your Wallet Charged Successfully',
  'home_my_room': 'Mine',
  "create_room": 'New ChatRoom',
  'login_with_password': "Enable password login",
  'login_with_password_disable': 'Disable password login',
  'change_password': 'Change Password',
  'account_password': 'Account Password',
  'enter_password': 'Enter Account Password',
  're_enter_password': 'Re-Enter Account Password',
  'id_login': 'Login using ID',
  'id_text': 'ID',





};