const Map<String, String> fr = {
 'about_us_title': 'À propos de l\'application',
  'about_us_version': 'Numéro de version',
  'about_us_update_version': 'Mettre à jour la version',
  'about_us_official_website': 'Site officiel',
  'account_management_title': 'Gestion de compte',
  'add_post': 'Publier',
  'add_post_msg': 'Votre publication sera examinée par un de nos modérateurs et sera bientôt acceptée.',
  'add_photo_gallery': 'Galerie de photos',
  'add_camera': 'Caméra',
  'add_status_my_status': 'Mon statut',
  'add_status_share': 'Partager',
  'add_status_msg': 'Statut mis à jour avec succès',
  'agreement_title': 'Conditions d\'utilisation',
  'agreement_user_agreement': 'Conditions d\'utilisation de LikLok',
  'edit_language': 'Langue',
  'edit_arabic': 'Arabe',
  'edit_profile_title': 'Modifier le profil',
  'edit_profile_Cover_photo': 'Photo de couverture',
  'edit_profile_upload': 'Télécharger',
  'edit_profile_basic_information': 'Informations de base',
  'edit_profile_user_name': 'Nom d\'utilisateur',
  'edit_profile_gender': 'Genre',
  'edit_profile_male': 'Homme',
  'edit_profile_female': 'Femme',
  'edit_profile_date_of_birth': 'Date de naissance',
  'edit_profile_country': 'Pays',
    'edit_profile_my_tags': 'Mes loisirs',
  'edit_profile_update': 'Mettre à jour',
  'edit_profile_tag_msg': 'Vos loisirs ont été mis à jour avec succès',
  'edit_profile_user_name_title': 'Nom d\'utilisateur',
  'edit_profile_characters !': 'Maximum 20 caractères !',
  'edit_profile_enter_user_name': 'Entrez le nom d\'utilisateur',
  'edit_profile_cancel': 'Annuler',
  'edit_profile_edit': 'Modifier',
  'edit_profile_photo_msg': 'Votre photo a été mise à jour !',
  'edit_profile_Cover_msg': 'Votre couverture a été mise à jour !',
  'followers_title': 'Abonnés',
  'following_title': 'Abonnements',
  'friends_title': 'Amis',
  'home_party': 'Fête',
  'home_discover': 'Découverte',
  'inner_report': 'Rapport',
  'inner_block': 'Bloquer',
  'inner_basic_information': 'Informations de base',
  'inner_room_gifts': 'Cadeaux de la chambre',
  'inner_my_frames': 'Mes cadres',
  'inner_cars_(Entries)': 'Voitures (Entrées)',
  'login_welcome_msg': 'Bienvenue sur LikLok !',
  'login_title': 'C\'est une question de plaisir !',
  'login_privacy': 'En vous inscrivant sur LikLok, vous acceptez cela',
  'login_policy': 'Politique de LikLok',
  'login_and': 'et',
  'login_services': 'Conditions d\'utilisation de LikLok',
  'mall_title': 'Magasin',
  'mall_purchase': 'Acheter',
  'mall_msg': 'Désolé, vous n\'avez pas assez d\'or !',
  'moments_recommend': 'Recommandé',
  'moments_mine': 'Mes publications',
  'moments_follow': 'Suivre',
  'moments_not_interested': 'Pas intéressé',
  'moments_report': 'Rapport',
  'my_designs_days': 'Jours :',
  'my_designs_use': 'Utilisation',
  'my_level_wealth': 'Contribution',
  'my_level_karizma': 'Kérizma',
  'my_level_charging': 'Recharge',
  'my_level_current_points': 'Points actuels',
  'my_level_next_level': 'Au niveau suivant',
  'my_level_ways_to_level_up': 'Façons de monter de niveau ?',
  'my_level_send_gift': 'Envoyer un cadeau à un ami dans la salle de chat',
  'my_level_gold_point': '1 or = 1 point',
  'my_level_receive': 'Recevoir un cadeau d\'un ami dans la salle de chat',
  'my_level_charge_your_gold': 'Rechargez votre or !',
  'network_title': 'Diagnostic réseau',
  'network_start': 'Démarrer',
  'notification_moments': 'Moments',
  'notification_profile': 'Profil',
  'notification_charging': 'Recharge',
  'notification_system': 'Système',
  'notification_announcement': 'Annonce',
  'notification_setting_title': 'Notifications',
  'notification_setting_private_chat': 'Chat privé',
  'notification_setting_new_followers': 'Nouveaux abonnés',
  'notification_setting_invitation_message': 'Message d\'invitation',
  'notification_setting_moments_notification': 'Notification de moments',
  'post_title': 'Contenu du moment',
  'post_label': 'Veuillez être amical !',
  'post_msg': 'Votre commentaire a été envoyé avec succès !',
  'privacy_policy_title': 'Politique de confidentialité',
  'privacy_policy': 'Politique de confidentialité de LikLok',
  'profile_msg_copied': 'Numéro ID copié !',
  'profile_visitors': 'Visiteurs',
  'profile_gold': 'Or',
  'profile_diamond': 'Diamant',
  'profile_room': 'Salle',
  'profile_gifts': 'Cadeaux',
  'profile_level': 'Niveau',
  'profile_my_posts': 'Mes publications',
  'profile_my_status': 'Mon statut',
  'profile_invite_friends': 'Inviter des amis',
  'profile_medals': 'Médailles',
  'profile_contact_us': 'Contactez-nous',
  'profile_terms_of_use': 'Conditions d\'utilisation',
  'profile_account_settings': 'Paramètres du compte',
  'search_user': 'Utilisateur',
  'search_label_search': 'Rechercher des utilisateurs par ID / nom',
  'setting_title': 'Paramètres',
  'setting_language': 'Langue',
  'setting_notification': 'Notifications',
  'setting_blocked_list': 'Liste des bloqués',
  'setting_identity_verification': 'Vérification d\'identité',
  'setting_clear_cache': 'Vider le cache',
  'setting_views': 'Vues',
  'taps_home': 'Accueil',
  'taps_chats': 'Chats',
  'taps_me': 'Moi',
  'add_post_label': 'Partagez votre avis sur le mur des moments !',
  'gift_one_or_more_user': 'Un utilisateur ou plus',
  'gift_all_mic_users': 'Tous les utilisateurs du microphone',
  'gift_all_room_users': 'Tous les utilisateurs de la salle',
  'gift_send_to_all_room_members': 'Envoyer à tous les membres de la salle',
  'gift_send': 'Envoyer',
  'menu_theme': 'Fond d\'écran',
  'menu_music': 'Musique',
  'menu_lucky_number': 'Numéro porte-bonheur',
  'menu_dice': 'Dé',
  'menu_lucky_bag': 'Sac de chance',
  'menu_settings': 'Paramètres',
  'room_info_room_name': 'Nom de la salle',
  'room_info_room_admin': 'Administrateur de la salle',
  'room_info_room_country': 'Pays de la salle',
  'room_settings': 'Paramètres de la salle',
  'room_settings_room_title': 'Nom de la salle',
  'room_settings_update': 'Mettre à jour',
  'room_settings_hello': 'Message de bienvenue',
  'room_settings_room_password': 'Mot de passe de la salle',
  'room_settings_room_admins': 'Administrateurs de la salle',
  'room_settings_room_block_list': 'Liste de blocage',
  'chats_massage': 'Messages',
  'chats_friends': 'Amis',
  'chats_event_message': 'Notifications d\'activités',
  'chats_club_chat_service': 'Service client',
  'chats_system_massage': 'Messages système',
  'room_members': 'Membres de la salle',
  'log_out': 'Déconnexion',
  'logout_msg': 'Voulez-vous vous déconnecter',
  'delete_account': 'Supprimer le compte',
  'delete_Account_msg': 'Voulez-vous supprimer le compte',
  'change_local': 'Changer de langue',
  'change_local_msg': 'Voulez-vous changer la langue de l\'application',
  'login_phone_title': 'Inscrivez-vous avec votre numéro de téléphone',
  'login_phone_hint': 'Entrez votre numéro avec l\'indicatif du pays',
  'send_btn': 'Envoyer',
  'verify_btn': 'Vérifier',
  'verify_phone_hint': 'Entrez le code d\'activation',
  'verify_phone_title': 'Activer votre numéro de téléphone',
  'room_close_keep': 'Enregistrer',
  'room_close_exit': 'Sortir',
  'edit_ok': 'D\'accord',
  'add_status_label_text': '#Partagez votre bio avec vos amis !',
  'invite_invite_friends': 'Invitez vos amis à LikLok et célébrez ensemble !',
  'invite_copy': 'Copier le lien d\'invitation',
  'inner_msg_followed': 'Vous avez suivi cet utilisateur',
  'inner_msg_unfollowed': 'Vous avez annulé le suivi de cet utilisateur',
  'inner_msg_no_room': 'Désolé, cet utilisateur n\'a pas de salle',
  'inner_msg_not_any_room': 'Désolé, cet utilisateur n\'est dans aucune salle',
  'chat_search_friend': 'Recherchez vos amis par ID / nom',
  'remote_app_msg': 'Vous avez signalé cet utilisateur !',
  'remote_app_msg_error': 'Erreur ! Quelque chose a mal tourné',
  'remote_app_msg_blocked': 'Vous avez bloqué cet utilisateur !',
  'remote_chat_msg_failed': 'Échec de l\'ouverture de la salle, veuillez contacter le support',
  'remote_design_msg_design': 'Définir le design sur par défaut',
  'contact_Us_title': 'Contactez-nous',
  'contact_Us_club_chat': 'Nous, chez LikLok, sommes heureux de vous aider et de répondre à vos demandes pour rendre votre expérience d\'utilisation de l\'application agréable, donc n\'hésitez pas à nous contacter si vous rencontrez un problème, nous sommes toujours à votre service 24 heures sur 24, 7 jours sur 7.',
  'contact_Us_social_media': 'Nous serions également ravis de vous suivre sur les réseaux sociaux',
  'verification_title': 'Vérification d\'identité',
  'verification_id_card': 'Veuillez joindre une photo de votre carte d\'identité',
  'verification_id_face': 'Photo du visage sur la carte d\'identité',
  'verification_id_back': 'Photo du dos de la carte d\'identité',
  'verification_verify': 'Confirmer',
  'clear_cash_msg': 'Le cache a été supprimé avec succès',
  'chats_update_data_msg': 'Mise à jour réussie',
  'event_message_title': 'Messages de notification',
  'customer_service_title': 'Service client',
  'delete_chat': 'Supprimer la conversation',
  'block_user': 'Bloquer',
  'user_app_blocked_title': 'Vous avez été bloqué !',
  'user_app_blocked_msg': 'Désolé, vous ne pouvez pas accéder à l\'application car vous avez été bloqué des services de l\'application. Vous pouvez contacter l\'administration pour plus de détails.',
  'recharge_gold': 'Recharger le solde d\'or',
  'diamond_exchange': 'Échanger le solde de diamants',
  'diamond_exchange_inp_hint': 'Entrez la valeur de l\'échange',
  'diamond_exchange_note': 'La valeur minimale d\'échange est de 100 diamants',
  'diamond_exchange_rules': 'Instructions pour échanger des diamants contre de l\'or',
  'wallet_diamond_rule1': 'Les cadeaux que vous recevez sont automatiquement convertis en diamants selon les pourcentages définis et convenus',
  'wallet_diamond_rule2': 'Le taux de conversion des diamants en or est',
  'exchanged_gold': 'Valeur de l\'or échangé :',
  'exchange_btn': 'Convertir en or',
  'details': 'Détails',
  'exchange_failed': 'Les diamants ne peuvent être échangés que si la valeur est de 100 diamants ou plus',
  'charging_details': 'Détails du chargement',
  'exchange_failed2': 'Désolé, votre solde de diamants ne le permet pas',
  'edit_profile_user_gender': 'Modifier le genre de l\'utilisateur',
  'vip': 'VIP',
  'vip_privileges': 'Privilèges VIP',
  'Vip_package': 'Forfait VIP',
  'car': 'Voiture',
  "medal": "Médaille",
  "special_msg": "Messages spéciaux",
  "entering_effect": "Effet d'entrée",
  "login_time": "Cacher la date d'inscription",
  "stop_track": "Empêcher le suivi",
  "no_kick": "Interdire le renvoi",
  "use_mic": "Monter sur le micro",
  "mic_closed_msg": "Désolé, ce micro est fermé",
  "un_use_mic": "Quitter le micro",
  "mute": "Mettre en sourdine",
  "lock_mic": "Verrouiller le micro",
  "lock_all_mics": "Verrouiller tous les micros",
  "unlock_mic": "Déverrouiller le micro",
  "unlock_all_mic": "Déverrouiller tous les micros",
  'remove_from_mic': "Retirer du micro",
  'chat_error': 'Erreur',
  'chat_loading': 'Chargement en cours',
  'inner_nothing': 'Rien ici',
  'inner_nothing_update': 'Rien ici, mettez à jour votre profil',
  'login_verify_phone': 'Désolé, nous ne pouvons pas vérifier le téléphone maintenant !',
  'login_code_msg': 'Le code de vérification a été envoyé avec succès',
  'network_msg': 'Tous les services réseau fonctionnent comme prévu',
  'splash_party': 'Fêtez autant que vous le pouvez',
  'musics2_model_add_music': 'Ajouter de la musique',
  'musics_model_my_music': 'Ma musique',
  'agency_charge_title': 'Recharger le solde du membre',
  'agency_charge_operation_title': 'Opérations de recharge',
  'agency_charge_search': 'Recherche',
  'agency_charge_charge': 'Recharger',
  'agency_charge_user_data': 'Données de l\'utilisateur',
  'join_host_title': 'Demande d\'adhésion à l\'agence',
  'join_host_request': 'Envoyer une demande d\'adhésion',
  'join_host_data': 'Données de l\'agence',
  'agency_income_title': 'Revenu de l\'hôte',
  'agency_income_target': 'Cible',
  'agency_income_work_hour': 'Nombre d\'heures de travail',
  'agency_income_hour': 'Heure : ',
  'agency_income_day': 'Jour : ',
  'agency_income_work_points': 'Nombre de points actuels',
  'agency_income_next_target': 'Restant pour atteindre l\'objectif suivant.',
  'agency_income_next_achieve_target': 'Restant pour atteindre le prochain objectif',
  'block_msg_unblocked': 'Vous avez débloqué cet utilisateur !',
  'chat_hint_text_form': 'Écrivez quelque chose ...',
  'chat_no_resents': 'Rien pour le moment',
  'room_close_mic': 'Désolé, ce microphone est fermé',
  'room_msg': "La direction de LikLok vous souhaite de passer de bons moments sur sa plateforme et souligne l'importance de maintenir des bonnes manières de communication entre tous les membres et d'éviter le harcèlement, tout en avertissant de ne pas cibler des sujets sensibles, politiques et religieux.",
  "notice": "Entrée de la salle : ",
  "user_enter_message": "Bonjour ...",
  "host_agency_search": "Recherche par ID d'agence",
  "request_process": "Votre demande est en cours de traitement",
"agency_members_title": "Membres de l'agence",
"choose_receiver": "Vous devez d'abord sélectionner un destinataire pour le cadeau",
"choose_gift": "Veuillez choisir un cadeau",
"daily": "Quotidien",
"weekly": "Hebdomadaire",
"monthly": "Mensuel",
"app_rank": "Coupe LikLok",
"room_remove_mic": "Désolé, l'administrateur vous a retiré du micro",
"music_error_permissions": "Impossible de télécharger des fichiers musicaux sans autorisation d'accès aux fichiers",
"unmute": "Activer le son",
"room_settings_room_subject": "Type de salle",
"room_settings_room_img": "Image de la salle",
"room_password_label": "Mot de passe de la salle",
"room_password_wrong": "Mot de passe incorrect",
"show_profile": "Afficher l'utilisateur",
"admin_mic_alert": "Désolé ! Micro réservé aux administrateurs uniquement",
"should_be_on_mic": "Désolé, vous devez être un utilisateur de micro !",
"add_admin": "Administrateur",
"add_admin_title": "Ajouter un administrateur à la salle",
"admin_added": "Un nouvel administrateur a été désigné",
"remove_btn": "Supprimer",
"admin_deleted": "Administrateur supprimé",
"room_save_dialog_title": "Annuler la sauvegarde de la salle",
"room_save_dialog_msg": "Voulez-vous annuler la sauvegarde de la salle ?",
"show_user": "Afficher l'utilisateur",
"counter_off": "Le compteur est désactivé",
"counter_on": "Le compteur est activé",
"kick_out": "Expulser",
"kick_out_hour": "Expulsion pour une heure",
"kick_out_day": "Expulsion pour un jour",
"kick_out_forever": "Expulsion permanente",
"local_lucky_case": "Caisse de chance locale",
"global_lucky_case": "Caisse de chance mondiale",
"benner_global_hint": "La caisse de chance mondiale sera affichée dans toutes les salles",
"benner_global_hint2": "Tout le monde peut ouvrir la caisse et obtenir de l'or",
"benner_local_hint": "La caisse de chance locale sera affichée dans la salle",
"lucky_case_msg": "Vous avez obtenu de la caisse de chance ",
"rollet_value": "Frais d'entrée",
"rollet_max_members": "Nombre maximum de participants",
"rollet_admin_play": "Je participe aussi",
"rollet_start": "Commencer",
"rollet_hint_text": "Il faut au moins deux personnes pour commencer le jeu et les autres ne peuvent pas rejoindre après le début du jeu",
"rollet_join": "Participer",
"no_active_rollet": "Aucune roulette active pour le moment",
"kickout_msg": "Vous avez été expulsé de la salle par l'administrateur",
"room_blocked_msg": "Désolé, vous ne pouvez pas entrer dans la salle pour le moment",
"unblock_btn": "Annuler le blocage",
"invite_link_copied": "Lien d'invitation de l'application copié",
"current_target": "Objectif actuel",
"non": "(Non spécifié)",
"next_target": "Prochain objectif",
"total_work_hours": "Nombre total d'heures de travail",
"total_work_days": "Nombre total de jours de travail",
"salary": "Salaire actuel",
"check_privacy": "Veuillez d'abord accepter la politique de confidentialité",
"no_data": "Aucune donnée à afficher !",
"help_title": "Centre d'aide",
"help_center_whatssapp": "Partagez-nous vos questions via WhatsApp",
"help_center_website": "Vous pouvez visiter notre site pour un meilleur service",
"help_center_email": "Ou vous pouvez obtenir de l'aide par e-mail",
"read_more": "Lire la suite",
"account_ban_title": "Votre compte a été bloqué",
"account_ban_msg": "Désolé, vous ne pouvez pas accéder à l'application avec ce compte car il a été bloqué pour violation des conditions d'utilisation",
"device_ban_title": "Votre téléphone a été bloqué",
"device_ban_msg": "Désolé, vous ne pouvez pas accéder à l'application avec ce téléphone car votre appareil a été bloqué pour violation des conditions d'utilisation",
"charge_title": "Recharge",
"get_8000_coins": "Obtenez 8000 unités d'or pour seulement 1 dollar",
"get_40000_coins": "Obtenez 40000 unités d'or pour seulement 5 dollars",
"get_160000_coins": "Obtenez 160000 unités d'or pour seulement 20 dollars",
"get_400000_coins": "Obtenez 400000 unités d'or pour seulement 50 dollars",
"get_800000_coins": "Obtenez 800000 unités d'or pour seulement 100 dollars",
"new_joiner": "Accepter l'adhésion",
"kik_member": "Expulser le membre",
"out_member": "Membre expulsé",
"accept_member_title": "Accepter l'adhésion d'un membre",
"accept_member_msg": "Voulez-vous accepter l'adhésion de ce membre ?",
"kik_member_title": "Expulser un membre",
"kik_member_msg": "Voulez-vous expulser ce membre ?",
"moments": "Moments",
"chats": "Messages",
"me": "Moi",
"game1": "Pierre Papier Ciseaux",
"balance_added": "Le solde a été ajouté avec succès",
"agency_statics_title": "Statistiques de l'agence",
"day_count": "Nombre de jours",
"point_count": "Nombre de points",
"agent_salary": "Salaire de l'agent",
"host_agent": "Salaire de l'hôte",
 'indian_lang': 'langue hindi',
 'phlpini_lang': 'Langue philippine',
 'pangladish_lang': 'langue bengali',
 'barazil_lang': 'Langue brésilienne (portugais)',
 'france_lang': 'Français',
 'games': 'Jeux',
 'chineese_lang':'langue chinoise',
 'indonisian_lang':'indonésien',
 'relations': 'Rapports'





};