const Map<String, String> hi = {
'about_us_title': 'ऐप के बारे में',
'about_us_version': 'संस्करण संख्या',
'about_us_update_version': 'संस्करण अपडेट',
'about_us_official_website': 'आधिकारिक वेबसाइट',
'account_management_title': 'खाता प्रबंधन',
'add_post': 'पोस्ट करें',
'add_post_msg': 'आपकी पोस्ट हमारे एक सुपरवाइज़र द्वारा समीक्षा की जाएगी और जल्द ही स्वीकृत की जाएगी',
'add_photo_gallery': 'फोटो गैलरी',
'add_camera': 'कैमरा',
'add_status_my_status': 'मेरा स्थिति',
'add_status_share': 'शेयर करें',
'add_status_msg': 'स्थिति सफलतापूर्वक अपडेट की गई',
'agreement_title': 'उपयोग की शर्तें',
'agreement_user_agreement': 'LikLok उपयोग शर्तें',
'edit_language': 'भाषा',
'edit_arabic': 'अरबी',
'edit_profile_title': 'प्रोफाइल संपादित करें',
'edit_profile_Cover_photo': 'कवर फोटो',
'edit_profile_upload': 'अपलोड करें',
'edit_profile_basic_information': 'बुनियादी जानकारी',
'edit_profile_user_name': 'उपयोगकर्ता नाम',
'edit_profile_gender': 'लिंग',
'edit_profile_male': 'पुरुष',
'edit_profile_female': 'महिला',
'edit_profile_date_of_birth': 'जन्म तिथि',
'edit_profile_country': 'देश',
'edit_profile_my_tags': 'मेरी रुचियाँ',
'edit_profile_update': 'अपडेट करें',
'edit_profile_tag_msg': 'आपकी रुचियाँ सफलतापूर्वक अपडेट की गईं',
'edit_profile_user_name_title': 'उपयोगकर्ता नाम',
'edit_profile_characters !': 'अधिकतम 20 वर्ण !',
'edit_profile_enter_user_name': 'उपयोगकर्ता नाम दर्ज करें',
'edit_profile_cancel': 'रद्द करें',
'edit_profile_edit': 'संपादित करें',
'edit_profile_photo_msg': 'आपकी फोटो अपडेट की गई!',
'edit_profile_Cover_msg': 'आपका कवर अपडेट किया गया!',
'followers_title': 'अनुयायी',
'following_title': "अनुकरण",
'friends_title': 'मित्र',
'home_party': 'पार्टी',
'home_discover': 'खोजें',
'inner_report': 'रिपोर्ट',
'inner_block': 'ब्लॉक',
'inner_basic_information': 'बुनियादी जानकारी',
'inner_room_gifts': 'कमरे के उपहार',
'inner_my_frames': 'मेरे फ्रेम',
'inner_cars_(Entries)': 'गाड़ियाँ (प्रविष्टियाँ)',
'login_welcome_msg': 'LikLok में आपका स्वागत है!',
'login_title': 'यह मज़े के बारे में है!',
'login_privacy': 'LikLok में पंजीकरण करके आप इस पर सहमति देते हैं',
'login_policy': 'LikLok नीति',
'login_and': 'और',
'login_services': 'LikLok उपयोग की शर्तें',
'mall_title': 'दुकान',
'mall_purchase': 'खरीदें',
'mall_msg': 'क्षमा करें, आपके पास पर्याप्त सोना नहीं है!',
'moments_recommend': 'सिफारिश की गई',
'moments_mine': 'मेरे पोस्ट',
'moments_follow': 'अनुकरण',
'moments_not_interested': 'रुचि नहीं',
'moments_report': 'रिपोर्ट',
'my_designs_days': 'दिन:',
'my_designs_use': 'उपयोग',
'my_level_wealth': 'योगदान',
'my_level_karizma': 'करिज्मा',
'my_level_charging': 'चार्जिंग',
'my_level_current_points': 'वर्तमान अंक',
'my_level_next_level': 'अगले स्तर तक',
'my_level_ways_to_level_up': 'स्तर बढ़ाने के तरीके?',
'my_level_send_gift': 'चैट रूम में एक दोस्त को उपहार भेजें',
'my_level_gold_point': '1 सोना = 1 अंक',
'my_level_receive': 'चैट रूम में एक दोस्त से उपहार प्राप्त करें',
'my_level_charge_your_gold': 'अपने सोने को चार्ज करें!',
'network_title': 'नेटवर्क诊断',
'network_start': 'शुरू करें',
'notification_moments': 'क्षण',
'notification_profile': 'प्रोफाइल',
'notification_charging': 'चार्जिंग',
'notification_system': 'सिस्टम',
'notification_announcement': 'घोषणा',
'notification_setting_title': 'सूचनाएं',
'notification_setting_private_chat': 'निजी चैट',
'notification_setting_new_followers': 'नए अनुयायी',
'notification_setting_invitation_message': 'आमंत्रण संदेश',
'notification_setting_moments_notification': 'क्षणों की सूचना',
'post_title': 'क्षण की सामग्री',
'post_label': 'कृपया मित्रवत रहें!',
'post_msg': 'आपका टिप्पणी सफलतापूर्वक भेजा गया!',
'privacy_policy_title': 'गोपनीयता नीति',
'privacy_policy': 'LikLok की गोपनीयता नीति',
'profile_msg_copied': 'आईडी नंबर कॉपी किया गया!',
'profile_visitors': 'दर्शक',
'profile_gold': 'सोना',
'profile_diamond': 'हीरा',
'profile_room': 'कमरा',
'profile_gifts': 'उपहार',
'profile_level': 'स्तर',
'profile_my_posts': 'मेरे पोस्ट',
'profile_my_status': 'मेरा स्थिति',
'profile_invite_friends': 'मित्रों को आमंत्रित करें',
'profile_medals': 'पदक',
'profile_contact_us': 'संपर्क करें',
'profile_terms_of_use': 'उपयोग की शर्तें',
'profile_account_settings': 'खाता सेटिंग्स',
'search_user': 'उपयोगकर्ता',
'search_label_search': 'आईडी / नाम द्वारा उपयोगकर्ताओं की खोज करें',
'setting_title': 'सेटिंग्स',
'setting_language': 'भाषा',
'setting_notification': 'सूचनाएं',
'setting_blocked_list': 'ब्लॉक सूची',
'setting_identity_verification': 'पहचान सत्यापन',
'setting_clear_cache': 'कैश साफ़ करें',
'setting_views': 'दृश्य',
'taps_home': 'होम',
'taps_chats': 'चैट',
'taps_me': 'मैं',
'add_post_label': 'क्षण की दीवार पर अपनी राय साझा करें!',
'gift_one_or_more_user': 'एक या अधिक उपयोगकर्ता',
'gift_all_mic_users': 'सभी माइक्रोफोन उपयोगकर्ता',
'gift_all_room_users': 'सभी कमरे के उपयोगकर्ता',
'gift_send_to_all_room_members': 'कमरे के सभी सदस्यों को भेजें',
'gift_send': 'भेजें',
'menu_theme': 'पृष्ठभूमि',
'menu_music': 'संगीत',
'menu_lucky_number': 'भाग्यशाली संख्या',
'menu_dice': 'डाइस',
'menu_lucky_bag': 'भाग्यशाली बैग',
'menu_settings': 'सेटिंग्स',
'room_info_room_name': 'कमरे का नाम',
'room_info_room_admin': 'कमरे का प्रशासक',
'room_info_room_country': 'कमरे का देश',
'room_settings': 'कमरे की सेटिंग्स',
'room_settings_room_title': 'कमरे का नाम',
'room_settings_update': 'अपडेट करें',
'room_settings_hello': 'स्वागत संदेश',
'room_settings_room_password': 'कमरे का पासवर्ड',
'room_settings_room_admins': 'कमरे के प्रशासक',
'room_settings_room_block_list': 'ब्लॉक सूची',
'chats_massage': 'संदेश',
'chats_friends': 'मित्र',
'chats_event_message': 'गतिविधियों की सूचनाएँ',
'chats_club_chat_service': 'ग्राहक सेवा',
'chats_system_massage': 'सिस्टम संदेश',
'room_members': "कमरे के सदस्य",
"log_out": "लॉग आउट",
"logout_msg": "क्या आप लॉग आउट करना चाहते हैं",
"delete_account": "खाता हटाएं",
"delete_Account_msg": "क्या आप खाता हटाना चाहते हैं",
"change_local": "भाषा बदलें",
"change_local_msg": "क्या आप ऐप की भाषा बदलना चाहते हैं",
"login_phone_title": "अपने मोबाइल नंबर से पंजीकरण करें",
'login_phone_hint': "अपने नंबर को देश कोड के साथ लिखें",
"send_btn": "भेजें",
"verify_btn": "सत्यापित करें",
"verify_phone_hint": "सत्यापन कोड दर्ज करें",
"verify_phone_title": "अपने मोबाइल नंबर को सक्रिय करें",
"room_close_keep": "सहेजें",
"room_close_exit": "निकालें",
'edit_ok': 'ठीक है',
'add_status_label_text': '#अपनी प्रोफ़ाइल अपने मित्रों के साथ साझा करें!',
'invite_invite_friends': 'अपने दोस्तों को LikLok पर आमंत्रित करें और एक साथ जश्न मनाएं!',
'invite_copy': 'आमंत्रण लिंक कॉपी करें',
'inner_msg_followed': 'आपने इस उपयोगकर्ता का पालन किया है',
'inner_msg_unfollowed': 'आपने इस उपयोगकर्ता का पालन समाप्त कर दिया है',
'inner_msg_no_room': 'क्षमा करें, इस उपयोगकर्ता के पास कोई कमरा नहीं है',
'inner_msg_not_any_room': 'क्षमा करें, इस उपयोगकर्ता का कोई कमरा नहीं है',
'chat_search_friend': 'अपने दोस्तों को आईडी / नाम द्वारा खोजें',
'remote_app_msg': 'आपने इस उपयोगकर्ता की रिपोर्ट की!',
'remote_app_msg_error ': 'त्रुटि! कुछ गलत हो गया',
'remote_app_msg_blocked': 'आपने इस उपयोगकर्ता को ब्लॉक कर दिया है!',
'remote_chat_msg_failed': 'कमरा खोलने में विफल, कृपया समर्थन से संपर्क करें',
'remote_design_msg_design': 'डिज़ाइन को डिफ़ॉल्ट मोड में सेट करें',
'contact_Us_title': 'संपर्क करें',
'contact_Us_club_chat': 'हम LikLok में आपकी सहायता करने और आपकी आवश्यकताओं को पूरा करने के लिए खुश हैं, इसलिए यदि आपको कोई समस्या है, तो कृपया हमसे संपर्क करें, हम हमेशा आपकी सेवा में हैं 24 घंटे सप्ताह के सभी दिनों में',
'contact_Us_social_media': 'हमें सोशल मीडिया पर फॉलो करना भी अच्छा लगेगा',
'verification_title': 'पहचान सत्यापन',
'verification_id_card': 'कृपया अपनी पहचान पत्र की तस्वीर संलग्न करें',
'verification_id_face': 'पहचान पत्र का चेहरा चित्र',
'verification_id_back': 'पहचान पत्र का पिछला चित्र',
'verification_verify': 'सत्यापित करें',
'clear_cash_msg': 'कैश सफलतापूर्वक हटा दिया गया',
'chats_update_data_msg': 'सफलता से अपडेट किया गया',
'event_message_title': 'सूचना संदेश',
'customer_service_title': 'ग्राहक सेवा',
'delete_chat': 'चैट हटाएं',
'block_user': 'ब्लॉक करें',
'user_app_blocked_title': 'आपको ब्लॉक कर दिया गया है!',
'user_app_blocked_msg': 'क्षम करें, आप ऐप में प्रवेश नहीं कर सकते क्योंकि आपको ऐप की सेवाओं का उपयोग करने से रोक दिया गया है। अधिक जानकारी के लिए प्रशासन से संपर्क करें।',
'recharge_gold': 'सोने का बैलेंस रिचार्ज करें',
"diamond_exchange": " हीरे के बैलेंस का विनिमय",
"diamond_exchange_inp_hint": " परिवर्तन की राशि लिखें",
"diamond_exchange_note": "न्यूनतम विनिमय राशि 100 हीरे है",
"diamond_exchange_rules": "हीरे को सोने में बदलने के निर्देश",
"wallet_diamond_rule1": "आपको प्राप्त उपहार स्वचालित रूप से निर्धारित और सहमत अनुपात में हीरों में परिवर्तित होते हैं",
"wallet_diamond_rule2": "हीरे को सोने में बदलने का अनुपात है",
"exchanged_gold": " परिवर्तित सोने की राशि: ",
"exchange_btn": "सोने में परिवर्तित करें",
"details": "विवरण",
"exchange_failed": "हीरे का विनिमय केवल तभी किया जा सकता है जब राशि 100 हीरे या उससे अधिक हो",
"charging_details": "चार्जिंग विवरण",
"exchange_failed2": "क्षम करें, आपके हीरे का बैलेंस अनुमति नहीं देता",
"edit_profile_user_gender": "उपयोगकर्ता का प्रकार संपादित करें",
"vip": "अरिस्टोक्रेसी",
"vip_privileges": "अरिस्टोक्रेसी के विशेषाधिकार",
"Vip_package": "अरिस्टोक्रेसी पैकेज",
"car": "गाड़ी",
"medal": "पदक",
"special_msg": "विशेष संदेश",
"entering_effect": "प्रवेश प्रभाव",
"login_time": "पंजीकरण तिथि छिपाएं",
"stop_track": "ट्रैकिंग बंद करें",
"no_kick": "निकालने से रोकें",
"use_mic": "माइक्रोफोन पर जाएं",
"mic_closed_msg": "क्षम करें, यह माइक्रोफोन बंद है",
"un_use_mic": "माइक्रोफोन से बाहर निकलें",
"mute": "मौन करें",
"lock_mic": "माइक्रोफोन बंद करें",
"lock_all_mics": "सभी माइक्रोफोनों को बंद करें",
"unlock_mic": "माइक्रोफोन खोलें",
"unlock_all_mic": "सभी माइक्रोफोनों को खोलें",
'remove_from_mic': "माइक्रोफोन से हटाएं",
'chat_error': 'त्रुटि',
'chat_loading': 'लोड हो रहा है',
'inner_nothing': 'यहाँ कुछ नहीं है',
'inner_nothing_update': 'यहाँ कुछ नहीं है, अपने प्रोफाइल को अपडेट करें',
'login_verify_phone': 'क्षम करें, हम अभी फोन की पुष्टि नहीं कर सकते!',
'login_code_msg': 'सत्यापन कोड सफलतापूर्वक भेजा गया',
'network_msg': 'सभी नेटवर्क सेवाएं अपेक्षित रूप से कार्य कर रही हैं',
'splash_party': 'जब भी संभव हो, जश्न मनाएं',
'musics2_model_add_music': 'संगीत जोड़ें',
'musics_model_my_music': 'संगीत',
'agency_charge_title': 'सदस्य का बैलेंस रिचार्ज करें',
'agency_charge_operation_title': 'रिचार्ज संचालन',
'agency_charge_search': 'खोजें',
'agency_charge_charge': 'रिचार्ज',
'agency_charge_user_data': 'उपयोगकर्ता डेटा',
'join_host_title': 'एजेंसी में शामिल होने का अनुरोध',
'join_host_request': 'शामिल होने का अनुरोध भेजें',
'join_host_data': 'एजेंसी डेटा',
'agency_income_title': 'होस्ट की आय',
'agency_income_target': 'लक्ष्य',
'agency_income_work_hour': 'कार्य के घंटे',
'agency_income_hour': 'घंटा: ',
'agency_income_day': 'दिन: ',
'agency_income_work_points': 'वर्तमान अंक संख्या',
'agency_income_next_target': 'अगले लक्ष्य को प्राप्त करने के लिए शेष।',
'agency_income_next_achieve_target': 'अगले लक्ष्य को प्राप्त करने के लिए शेष',
'block_msg_unblocked': 'आपने इस उपयोगकर्ता को अनब्लॉक कर दिया है!',
'chat_hint_text_form': 'कुछ लिखें ...',
'chat_no_resents': 'वर्तमान में कोई नहीं है',
'room_close_mic': 'क्षम करें, यह माइक्रोफोन बंद है',
'room_msg': "LikLok प्रबंधन आपको उनके प्लेटफॉर्म पर अच्छा समय बिताने की शुभकामना देता है और सभी सदस्यों के बीच संवाद के शिष्टाचार को बनाए रखने और उत्पीड़न से बचने पर जोर देता है, और संवेदनशील, राजनीतिक और धार्मिक विषयों को लक्षित करने से चेतावनी देता है।",
"notice": "कमरे में प्रवेश: ",
"user_enter_message": "नमस्ते ...",
"host_agency_search": "एजेंसी आईडी द्वारा खोजें",
"request_process": "आपका अनुरोध अब संसाधित हो रहा है",
"agency_members_title": "एजेंसी सदस्य",
"choose_receiver": "पहले उपहार का रिसीवर चुनें",
"choose_gift": "कृपया उपहार चुनें",
"daily": "दैनिक",
"weekly": "साप्ताहिक",
"monthly": "मासिक",
"app_rank": "LikLok ट्रॉफी",
"room_remove_mic": "क्षम करें, प्रशासक ने आपको माइक्रोफोन से हटा दिया है",
"music_error_permissions": "फ़ाइलों तक पहुँचने की अनुमति दिए बिना संगीत फ़ाइलें अपलोड नहीं की जा सकतीं",
"unmute": "ध्वनि चालू करें",
"room_settings_room_subject": "कमरे का प्रकार",
"room_settings_room_img": "कमरे की छवि",
"room_password_label": "कमरे का पासवर्ड",
"room_password_wrong": "गलत पासवर्ड",
"show_profile": "उपयोगकर्ता दिखाएं",
"admin_mic_alert": "क्षम करें! यह माइक्रोफोन केवल प्रबंधकों के लिए है",
"should_be_on_mic": "क्षम करें, आपको माइक्रोफोन का उपयोगकर्ता होना चाहिए!",
"add_admin": "प्रबंधक",
"add_admin_title": "कमरे के लिए प्रबंधक जोड़ें",
"admin_added": "नया प्रबंधक नियुक्त किया गया",
"remove_btn": "हटाएं",
"admin_deleted": "प्रबंधक को हटा दिया गया",
"room_save_dialog_title": "कमरे को सहेजना रद्द करें",
"room_save_dialog_msg": "क्या आप कमरे के संरक्षण को रद्द करना चाहते हैं",
"show_user": "उपयोगकर्ता दिखाएं",
"counter_off": "गिनती बंद",
"counter_on": "गिनती चालू",
"kick_out": "निकालें",
"kick_out_hour": "एक घंटे के लिए निकालें",
"kick_out_day": "एक दिन के लिए निकालें",
"kick_out_forever": "स्थायी रूप से निकालें",
"local_lucky_case": "स्थानीय भाग्य का बॉक्स",
"global_lucky_case": "वैश्विक भाग्य का बॉक्स",
"benner_global_hint": "वैश्विक भाग्य का बॉक्स सभी कमरों में दिखाई देगा",
"benner_global_hint2": "कोई भी इस बॉक्स को खोल सकता है और सोना प्राप्त कर सकता है",
"benner_local_hint": "स्थानीय भाग्य का बॉक्स कमरे के भीतर दिखाई देगा",
"lucky_case_msg": "आपने भाग्य के बॉक्स से प्राप्त किया ",
"rollet_value": "प्रवेश शुल्क",
"rollet_max_members": "अधिकतम प्रतिभागी संख्या",
"rollet_admin_play": "मैं भी भाग लेता हूँ",
"rollet_start": "शुरू करें",
"rollet_hint_text": "खेल शुरू करने के लिए कम से कम दो लोग चाहिए और खेल शुरू होने के बाद अन्य शामिल नहीं हो सकते",
"rollet_join": "भाग लें",
"no_active_rollet": "वर्तमान में कोई रोलट नहीं है",
"kickout_msg": "आपको प्रशासक द्वारा कमरे से बाहर निकाल दिया गया",
"room_blocked_msg": "क्षम करें, आप वर्तमान में कमरे में प्रवेश नहीं कर सकते",
"unblock_btn": "प्रतिबंध हटाएं",
"invite_link_copied": "ऐप का निमंत्रण लिंक कॉपी कर लिया गया",
"current_target": "वर्तमान लक्ष्य",
"non": "(निर्धारित नहीं)",
"next_target": "अगला लक्ष्य",
"total_work_hours": "कुल कार्य घंटों की संख्या",
"total_work_days": "कुल कार्य दिनों की संख्या",
"salary": "वर्तमान वेतन",
"check_privacy": "कृपया पहले गोपनीयता नीति को स्वीकार करें",
"no_data": "दिखाने के लिए कोई डेटा नहीं है!",
"help_title": "सहायता केंद्र",
"help_center_whatssapp": "अपने प्रश्न को व्हाट्सएप पर साझा करें",
"help_center_website": "आप बेहतर सेवा के लिए हमारी वेबसाइट पर जा सकते हैं",
"help_center_email": "या आप ईमेल के माध्यम से सहायता प्राप्त कर सकते हैं",
"read_more": "और पढ़ें",
"account_ban_title": "आपका खाता प्रतिबंधित कर दिया गया है",
"account_ban_msg": "क्षम करें, आपको इस खाते का उपयोग करके ऐप में प्रवेश करने की अनुमति नहीं है क्योंकि आपका खाता उपयोग की शर्तों का उल्लंघन करने के कारण प्रतिबंधित कर दिया गया है",
"device_ban_title": "आपका फोन प्रतिबंधित कर दिया गया है",
"device_ban_msg": "क्षम करें, आपको इस फोन का उपयोग करके ऐप में प्रवेश करने की अनुमति नहीं है क्योंकि आपका डिवाइस उपयोग की शर्तों का उल्लंघन करने के कारण प्रतिबंधित कर दिया गया है",
"charge_title": "चार्जिंग",
"get_8000_coins": "केवल 1 डॉलर में 8000 स्वर्ण इकाइयाँ प्राप्त करें",
"get_40000_coins": "केवल 5 डॉलर में 40000 स्वर्ण इकाइयाँ प्राप्त करें",
"get_160000_coins": "केवल 20 डॉलर में 160000 स्वर्ण इकाइयाँ प्राप्त करें",
"get_400000_coins": "केवल 50 डॉलर में 400000 स्वर्ण इकाइयाँ प्राप्त करें",
"get_800000_coins": "केवल 100 डॉलर में 800000 स्वर्ण इकाइयाँ प्राप्त करें",
"new_joiner": "शामिल होने की स्वीकृति",
"kik_member": "सदस्य को निकालें",
"out_member": 'निकाला गया सदस्य',
"accept_member_title": "सदस्य की स्वीकृति",
"accept_member_msg": 'क्या आप सदस्य की स्वीकृति चाहते हैं',
"kik_member_title": "सदस्य को निकालें",
"kik_member_msg": "क्या आप इस सदस्य को निकालना चाहते हैं",
"moments": "क्षण",
"chats": "संदेश",
"me": "मैं",
"game1": "पत्थर, कागज़, कैंची",
"balance_added": "शेष राशि सफलतापूर्वक जोड़ी गई",
"agency_statics_title": "एजेंसी के आँकड़े",
"day_count": "दिनों की संख्या",
"point_count": "अंक संख्या",
"agent_salary": "एजेंट का वेतन",
"host_agent": "होस्ट का वेतन",
  'indian_lang': 'हिंदी भाषा',
  'phlpini_lang': 'फिलिपिनो भाषा',
  'pangladish_lang': 'बंगाली भाषा',
  'barazil_lang': 'ब्राज़ीलियाई भाषा (पुर्तगाली)',
  'france_lang': 'फ़्रेंच',
  'games': 'खेल',
  'chineese_lang':'चीनी भाषा',
  'indonisian_lang':'इन्डोनेशियाई',
  'relations': 'संबंध',
  'accept_btn': 'स्वीकार',
  'cancel_btn': 'अस्वीकार करना',
  'relation_dialog_title':'किसी मित्र के साथ रिश्ते को स्वीकार या अस्वीकार करें',
  'relation_dialog_msg': 'कृपया अपने मित्र द्वारा भेजे गए रिश्ते को स्वीकार या अस्वीकार करें',
  'Wallet_Charged_successfully': 'आपका वॉलेट सफलतापूर्वक चार्ज हो गया',
  'home_my_room': 'मेरा',
  "create_room": 'नहीं, मैं अच्छा नहीं हूं.',
  'login_with_password': "पासवर्ड लॉगिन सक्षम करें",
  'login_with_password_disable': "पासवर्ड लॉगिन अक्षम करें",
  'change_password': 'पासवर्ड बदलें',
  'account_password': 'खाते का पासवर्ड',
  'enter_password': "खाता पासवर्ड दर्ज करें" ,
  're_enter_password': 'खाता पासवर्ड पुनः दर्ज करें',
  'id_login': "आईडी का उपयोग करके लॉगिन करें",
  'id_text': 'ID',


};