const Map<String, String> id = {
  'about_us_title': 'Tentang Aplikasi',
  'about_us_version': 'Nomor Versi',
  'about_us_update_version': 'Perbarui Versi',
  'about_us_official_website': 'Situs Resmi',
  'account_management_title': 'Manajemen Akun',
  'add_post': 'Posting',
  'add_post_msg': 'Postingan Anda akan ditinjau oleh salah satu moderator kami dan akan diterima segera',
  'add_photo_gallery': 'Galeri Foto',
  'add_camera': 'Kamera',
  'add_status_my_status': 'Status Saya',
  'add_status_share': 'Bagikan',
  'add_status_msg': 'Status Anda telah diperbarui dengan sukses',
  'agreement_title': 'Perjanjian Penggunaan',
  'agreement_user_agreement': 'Perjanjian Penggunaan LikLok',
  'edit_language': 'Bahasa',
  'edit_arabic': 'Arab',
  'edit_profile_title': 'Edit Profil',
  'edit_profile_Cover_photo': 'Foto Sampul',
  'edit_profile_upload': 'Unggah',
  'edit_profile_basic_information': 'Informasi Dasar',
  'edit_profile_user_name': 'Nama Pengguna',
  'edit_profile_gender': 'Jenis Kelamin',
  'edit_profile_male': 'Pria',
  'edit_profile_female': 'Wanita',
  'edit_profile_date_of_birth': 'Tanggal Lahir',
  'edit_profile_country': 'Negara',
  'edit_profile_my_tags': 'Hobi Saya',
  'edit_profile_update': 'Perbarui',
  'edit_profile_tag_msg': 'Hobi Anda telah diperbarui dengan sukses',
  'edit_profile_user_name_title': 'Nama Pengguna',
  'edit_profile_characters !': 'Maksimal 20 Karakter !',
  'edit_profile_enter_user_name': 'Masukkan Nama Pengguna',
  'edit_profile_cancel': 'Batal',
  'edit_profile_edit': 'Edit',
  'edit_profile_photo_msg': 'Foto Anda telah diperbarui!',
  'edit_profile_Cover_msg': 'Sampul Anda telah diperbarui!',
  'followers_title': 'Pengikut',
  'following_title': 'Mengikuti',
  'friends_title': 'Teman',
  'home_party': 'Pesta',
  'home_discover': 'Temukan',
  'inner_report': 'Laporan',
  'inner_block': 'Blokir',
  'inner_basic_information': 'Informasi Dasar',
  'inner_room_gifts': 'Kamar Hadiah',
  'inner_my_frames': 'Kerangka Saya',
  'inner_cars_(Entries)': 'Mobil (Masukan)',
  'login_welcome_msg': 'Selamat datang di LikLok!',
  'login_title': 'Ini Tentang Keseruan!',
  'login_privacy': 'Dengan mendaftar di LikLok, Anda setuju dengan ini',
  'login_policy': 'Kebijakan LikLok',
'login_and': 'dan',
  'login_services': 'Syarat Penggunaan LikLok',
  'mall_title': 'Toko',
  'mall_purchase': 'Beli',
  'mall_msg': 'Maaf, Anda tidak memiliki cukup emas!',
  'moments_recommend': 'Direkomendasikan',
  'moments_mine': 'Postingan Saya',
  'moments_follow': 'Ikuti',
  'moments_not_interested': 'Tidak Tertarik',
  'moments_report': 'Laporan',
  'my_designs_days': 'Hari:',
  'my_designs_use': 'Menggunakan',
  'my_level_wealth': 'Kontribusi',
  'my_level_karizma': 'Karizma',
  'my_level_charging': 'Isi Ulang',
  'my_level_current_points': 'Poin Saat Ini',
  'my_level_next_level': 'Menuju Level Berikutnya',
  'my_level_ways_to_level_up': 'Cara Menaikkan Level?',
  'my_level_send_gift': 'Kirim Hadiah ke Teman di Ruang Obrolan',
  'my_level_gold_point': '1 Emas = 1 Poin',
  'my_level_receive': 'Terima Hadiah dari Teman di Ruang Obrolan',
  'my_level_charge_your_gold': 'Isi Emas Anda!',
  'network_title': 'Diagnosa Jaringan',
  'network_start': 'Mulai',
  'notification_moments': 'Momen',
  'notification_profile': 'Profil',
  'notification_charging': 'Pengisian',
  'notification_system': 'Sistem',
  'notification_announcement': 'Pengumuman',
  'notification_setting_title': 'Notifikasi',
  'notification_setting_private_chat': 'Obrolan Pribadi',
  'notification_setting_new_followers': 'Pengikut Baru',
  'notification_setting_invitation_message': 'Pesan Undangan',
  'notification_setting_moments_notification': 'Notifikasi Momen',
  'post_title': 'Konten Momen',
  'post_label': 'Harap bersikap ramah!',
  'post_msg': 'Komentar Anda telah berhasil dikirim!',
  'privacy_policy_title': 'Kebijakan Privasi',
  'privacy_policy': 'Kebijakan Privasi LikLok',
  'profile_msg_copied': 'ID nomor telah disalin!',
  'profile_visitors': 'Pengunjung',
  'profile_gold': 'Emas',
  'profile_diamond': 'Berlian',
  'profile_room': 'Ruang',
  'profile_gifts': 'Hadiah',
  'profile_level': 'Level',
  'profile_my_posts': 'Postingan Saya',
  'profile_my_status': 'Status Saya',
  'profile_invite_friends': 'Undang Teman',
  'profile_medals': 'Medali',
  'profile_contact_us': 'Hubungi Kami',
  'profile_terms_of_use': 'Syarat Penggunaan',
  'profile_account_settings': 'Pengaturan Akun',
  'search_user': 'Pengguna',
  'search_label_search': 'Cari pengguna berdasarkan ID / nama',
  'setting_title': 'Pengaturan',
  'setting_language': 'Bahasa',
  'setting_notification': 'Notifikasi',
  'setting_blocked_list': 'Daftar yang Diblokir',
  'setting_identity_verification': 'Verifikasi Identitas',
  'setting_clear_cache': 'Hapus Cache',
  'setting_views': 'Tampilan',
  'taps_home': 'Beranda',
  'taps_chats': 'Obrolan',
  'taps_me': 'Saya',
  'add_post_label': 'Bagikan pendapat Anda di dinding momen!',
  'gift_one_or_more_user': 'Satu atau lebih pengguna',
  'gift_all_mic_users': 'Semua pengguna mikrofon',
  'gift_all_room_users': 'Semua pengguna ruang',
  'gift_send_to_all_room_members': 'Kirim ke semua anggota ruang',
  'gift_send': 'Kirim',
  'menu_theme': 'Latar Belakang',
  'menu_music': 'Musik',
  'menu_lucky_number': 'Nomor Keberuntungan',
  'menu_dice': 'Dadu',
  'menu_lucky_bag': 'Kantong Keberuntungan',
  'menu_settings': 'Pengaturan',
  'room_info_room_name': 'Nama Ruang',
  'room_info_room_admin': 'Admin Ruang',
  'room_info_room_country': 'Negara Ruang',
  'room_settings': 'Pengaturan Ruang',
  'room_settings_room_title': 'Nama Ruang',
  'room_settings_update': 'Perbarui',
  'room_settings_hello': 'Pesan Sambutan',
  'room_settings_room_password': 'Kata Sandi Ruang',
  'room_settings_room_admins': 'Admin Ruang',
  'room_settings_room_block_list': 'Daftar Blokir',
  'chats_massage': 'Pesan',
  'chats_friends': 'Teman',
  'chats_event_message': 'Notifikasi Kegiatan',
  'chats_club_chat_service': 'Layanan Pelanggan',
  'chats_system_massage': 'Pesan Sistem',
  'room_members': 'Anggota Ruang',
  'log_out': 'Keluar',
  'logout_msg': 'Apakah Anda ingin keluar?',
  'delete_account': 'Hapus Akun',
  'delete_Account_msg': 'Apakah Anda ingin menghapus akun?',
  'change_local': 'Ubah Bahasa',
  'change_local_msg': 'Apakah Anda ingin mengubah bahasa aplikasi?',
  'login_phone_title': 'Daftar dengan Nomor Telepon Anda',
  'login_phone_hint': 'Tulis nomor Anda dengan kode negara',
  'send_btn': 'Kirim',
  'verify_btn': 'Verifikasi',
  'verify_phone_hint': 'Masukkan kode aktivasi',
  'verify_phone_title': 'Aktivasi Nomor Telepon Anda',
  'room_close_keep': 'Simpan',
  'room_close_exit': 'Keluar',
  'edit_ok': 'Oke',
  'add_status_label_text': '#Bagikan biodata Anda dengan teman-teman!',
  'invite_invite_friends': 'Undang teman-teman Anda ke LikLok dan rayakan bersama!',
  'invite_copy': 'Salin Tautan Undangan',
  'inner_msg_followed': 'Anda telah mengikuti pengguna ini',
  'inner_msg_unfollowed': 'Anda telah berhenti mengikuti pengguna ini',
  'inner_msg_no_room': 'Maaf, pengguna ini tidak memiliki ruang',
  'inner_msg_not_any_room': 'Maaf, pengguna ini tidak berada di ruang mana pun',
  'chat_search_friend': 'Cari teman Anda dengan ID / nama',
  'remote_app_msg': 'Anda telah melaporkan pengguna ini!',
  'remote_app_msg_error ': 'Kesalahan! Terjadi kesalahan',
  'remote_app_msg_blocked': 'Anda telah memblokir pengguna ini!',
  'remote_chat_msg_failed': 'Gagal membuka ruang, silakan hubungi dukungan',
  'remote_design_msg_design': 'Atur desain ke mode default',
  'contact_Us_title': 'Hubungi Kami',
  'contact_Us_club_chat': 'Kami di LikLok senang membantu Anda dan memenuhi permintaan Anda serta membuat pengalaman penggunaan aplikasi Anda menyenangkan, jadi jangan ragu untuk menghubungi kami jika Anda mengalami masalah, kami selalu siap membantu 24 jam sehari, 7 hari seminggu.',
  'contact_Us_social_media': 'Kami juga senang jika Anda mengikuti kami di media sosial',
  'verification_title': 'Verifikasi Identitas',
  'verification_id_card': 'Silakan lampirkan foto kartu identitas Anda',
  'verification_id_face': 'Foto wajah kartu identitas',
  'verification_id_back': 'Foto belakang kartu identitas',
  'verification_verify': 'Konfirmasi',
  'clear_cash_msg': 'Cache telah dihapus dengan sukses',
  'chats_update_data_msg': 'Diperbarui dengan sukses',
  'event_message_title': 'Pesan Pemberitahuan',
  'customer_service_title': 'Layanan Pelanggan',
  'delete_chat': 'Hapus Percakapan',
  'block_user': 'Blokir',
  'user_app_blocked_title': 'Anda telah diblokir!',
  'user_app_blocked_msg': 'Maaf, Anda tidak dapat mengakses aplikasi karena Anda telah diblokir dari menggunakan layanan aplikasi. Anda dapat menghubungi administrasi untuk informasi lebih lanjut.',
  'recharge_gold': 'Isi Ulang Saldo Emas',
  "diamond_exchange": "Tukar Saldo Berlian",
  "diamond_exchange_inp_hint": "Masukkan nilai transfer",
  "diamond_exchange_note": "Nilai minimum untuk transfer adalah 100 berlian",
  "diamond_exchange_rules": "Instruksi untuk Mengubah Berlian Menjadi Emas",
  "wallet_diamond_rule1": "Hadiah yang Anda terima akan secara otomatis diubah menjadi berlian dengan persentase yang ditentukan dan disepakati",
  "wallet_diamond_rule2": "Persentase konversi berlian menjadi emas adalah",
  "exchanged_gold": "Nilai emas yang ditukar:",
  "exchange_btn": "Tukar Menjadi Emas",
  "details": "Rincian",
  "exchange_failed": "Berlian hanya dapat ditukar jika nilainya 100 berlian atau lebih",
  "charging_details": "Rincian Pengisian",
  "exchange_failed2": "Maaf, saldo berlian Anda tidak mencukupi",
  "edit_profile_user_gender": "Ubah Jenis Pengguna",
  "vip": "Aristokrasi",
  "vip_privileges": "Hak Istimewa Aristokrasi",
  "Vip_package": "Paket Aristokrasi",
  "car": "Mobil",
  "medal": "Medali",
  "special_msg": "Pesan Khusus",
  "entering_effect": "Efek Masuk",
  "login_time": "Sembunyikan Tanggal Pendaftaran",
  "stop_track": "Hentikan Pelacakan",
  "no_kick": "Hentikan Pengusiran",
  "use_mic": "Naik ke Mikrofon",
  "mic_closed_msg": "Maaf, mikrofon ini tertutup",
  "un_use_mic": "Keluar dari Mikrofon",
  "mute": "Diamkan Suara",
  "lock_mic": "Kunci Mikrofon",
  "lock_all_mics": "Kunci Semua Mikrofon",
  "unlock_mic": "Buka Kunci Mikrofon",
  "unlock_all_mic": "Buka Kunci Semua Mikrofon",
  'remove_from_mic': "Hapus dari Mikrofon",
  'chat_error': 'Kesalahan',
  'chat_loading': 'Sedang Memuat',
  'inner_nothing': 'Tidak Ada di Sini',
  'inner_nothing_update': 'Tidak ada di sini, perbarui biodata Anda',
  'login_verify_phone': 'Maaf, kami tidak dapat memverifikasi telepon saat ini!',
  'login_code_msg': 'Kode verifikasi telah dikirim dengan sukses',
  'network_msg': 'Semua layanan jaringan berjalan seperti yang diharapkan',
  'splash_party': 'Rayakan setiap kali Anda bisa',
  'musics2_model_add_music': 'Tambah Musik',
  'musics_model_my_music': 'Musik Saya',
  'agency_charge_title': 'Isi Ulang Saldo Anggota',
  'agency_charge_operation_title': 'Operasi Pengisian',
  'agency_charge_search': 'Cari',
  'agency_charge_charge': 'Isi Ulang',
  'agency_charge_user_data': 'Data Pengguna',
  'join_host_title': 'Permintaan Bergabung dengan Agensi',
  'join_host_request': 'Kirim Permintaan Bergabung',
  'join_host_data': 'Data Agensi',
  'agency_income_title': 'Pendapatan Host',
  'agency_income_target': 'Target',
  'agency_income_work_hour': 'Jumlah Jam Kerja',
  'agency_income_hour': 'Jam:',
  'agency_income_day': 'Hari:',
  'agency_income_work_points': 'Jumlah Poin Saat Ini',
  'agency_income_next_target': 'Sisa untuk mencapai target berikutnya.',
  'agency_income_next_achieve_target': 'Sisa untuk mencapai target berikutnya',
  'block_msg_unblocked': 'Anda telah membatalkan blokir pengguna ini!',
  'chat_hint_text_form': 'Tulis sesuatu...',
  'chat_no_resents': 'Saat ini tidak ada',
  'room_close_mic': 'Maaf, mikrofon ini tertutup',
  'room_msg': "Manajemen LikLok berharap Anda memiliki waktu yang menyenangkan di platformnya dan menegaskan pentingnya menjaga etika komunikasi antara semua anggota dan menghindari gangguan serta memperingatkan untuk tidak menargetkan topik sensitif, politik, dan agama.",
  "notice": "Masuk ke ruang:",
  "user_enter_message": "Halo...",
  "host_agency_search": "Cari dengan ID Agensi",
  "request_process": "Permintaan Anda sedang diproses sekarang",
  "agency_members_title": "Anggota Agensi",
  "choose_receiver": "Anda harus menentukan penerima hadiah terlebih dahulu",
  "choose_gift": "Silakan pilih hadiah",
  "daily": "Harian",
  "weekly": "Mingguan",
  "monthly": "Bulanan",
  "app_rank": "Peringkat LikLok",
  "room_remove_mic": "Maaf, admin telah menurunkan Anda dari mikrofon",
  "music_error_permissions": "Tidak dapat mengunggah file musik tanpa memberikan izin akses ke file",
  "unmute": "Nyalakan Suara",
  "room_settings_room_subject": "Jenis Ruang",
  "room_settings_room_img": "Gambar Ruang",
  "room_password_label": "Kata Sandi Ruang",
  "room_password_wrong": "Kata sandi salah",
  "show_profile": "Tampilkan Pengguna",
  "admin_mic_alert": "Maaf! Mikrofon hanya untuk administrator",
  "should_be_on_mic": "Maaf, Anda harus menjadi pengguna mikrofon!",
  "add_admin": "Admin",
  "add_admin_title": "Tambah Administrator untuk Ruang",
  "admin_added": "Administrator baru telah ditambahkan",
  "remove_btn": "Hapus",
  "admin_deleted": "Administrator telah dihapus",
  "room_save_dialog_title": "Batalkan Penyimpanan Ruang",
  "room_save_dialog_msg": "Apakah Anda ingin membatalkan penyimpanan ruang?",
  "show_user": "Tampilkan Pengguna",
  "counter_off": "Penghitung dimatikan",
  "counter_on": "Penghitung diaktifkan",
  "kick_out": "Usir",
  "kick_out_hour": "Usir selama satu jam",
  "kick_out_day": "Usir selama satu hari",
  "kick_out_forever": "Usir selamanya",
  "local_lucky_case": "Kotak Keberuntungan Lokal",
  "global_lucky_case": "Kotak Keberuntungan Global",
  "benner_global_hint": "Kotak keberuntungan global akan ditampilkan di semua ruangan",
  "benner_global_hint2": "Siapa saja bisa membuka kotak dan mendapatkan emas",
  "benner_local_hint": "Kotak keberuntungan lokal akan ditampilkan di dalam ruangan",
  "lucky_case_msg": "Anda mendapatkan dari kotak keberuntungan:",
  "rollet_value": "Biaya Masuk",
  "rollet_max_members": "Jumlah Peserta Maksimal",
  "rollet_admin_play": "Saya juga ikut bermain",
  "rollet_start": "Mulai",
  "rollet_hint_text": "Dibutuhkan setidaknya dua orang untuk memulai permainan dan tidak ada orang lain yang bisa bergabung setelah permainan dimulai",
  "rollet_join": "Ikut",
  "no_active_rollet": "Saat ini tidak ada roulette",
  "kickout_msg": "Anda telah diusir dari ruangan oleh admin",
  "room_blocked_msg": "Maaf, Anda tidak dapat masuk ke ruangan saat ini",
  "unblock_btn": "Batalkan Blokir",
  "invite_link_copied": "Tautan undangan aplikasi telah disalin",
  "current_target": "Target Saat Ini",
  "non": "(Tidak ditentukan)",
  "next_target": "Target Berikutnya",
  "total_work_hours": "Total Jam Kerja",
  "total_work_days": "Total Hari Kerja",
  "salary": "Gaji Saat Ini",
  "check_privacy": "Silakan setujui kebijakan privasi terlebih dahulu",
  "no_data": "Tidak ada data untuk ditampilkan!",
  "help_title": "Pusat Bantuan",
  "help_center_whatssapp": "Kirim pertanyaan Anda melalui WhatsApp",
  "help_center_website": "Anda dapat mengunjungi situs kami untuk layanan yang lebih baik",
  "help_center_email": "Atau Anda dapat menerima dukungan melalui email",
  "read_more": "Baca lebih lanjut",
  "account_ban_title": "Akun Anda Diblokir",
  "account_ban_msg": "Maaf, Anda tidak diizinkan untuk masuk ke aplikasi ini dengan akun ini karena akun Anda telah diblokir karena melanggar syarat penggunaan.",
  "device_ban_title": "Telepon Anda Diblokir",
  "device_ban_msg": "Maaf, Anda tidak diizinkan untuk masuk ke aplikasi ini dengan telepon ini karena perangkat Anda telah diblokir karena melanggar syarat penggunaan.",
  "charge_title": "Pengisian",
  "get_8000_coins": "Dapatkan 8000 koin hanya dengan 1 dolar",
  "get_40000_coins": "Dapatkan 40000 koin hanya dengan 5 dolar",
  "get_160000_coins": "Dapatkan 160000 koin hanya dengan 20 dolar",
  "get_400000_coins": "Dapatkan 400000 koin hanya dengan 50 dolar",
  "get_800000_coins": "Dapatkan 800000 koin hanya dengan 100 dolar",
  "new_joiner": "Terima Bergabung",
  "kik_member": "Usir Anggota",
  "out_member": "Anggota yang Dibuang",
  "accept_member_title": "Terima Bergabung Anggota",
  "accept_member_msg": "Apakah Anda ingin menerima anggota yang bergabung?",
  "kik_member_title": "Usir Anggota",
  "kik_member_msg": "Apakah Anda ingin mengusir anggota ini?",
  "moments": "Momen",
  "chats": "Pesan",
  "me": "Saya",
  "game1": "Batu Kertas Gunting",
  "balance_added": "Saldo berhasil ditambahkan",
  "agency_statics_title": "Statistik Agensi",
  "day_count": "Jumlah Hari",
  "point_count": "Jumlah Poin",
  "agent_salary": "Gaji Agen",
  "host_agent": "Gaji Host",
  'relations': 'hubungan',
  'accept_btn': 'penerimaan',
  'cancel_btn': 'untuk menolak',
  'relation_dialog_title':'Menerima atau menolak hubungan dengan teman',
  'relation_dialog_msg': 'Silakan terima atau tolak relasi yang dikirimkan oleh teman Anda',
  'Wallet_Charged_successfully': 'Dompet Anda Berhasil Diisi Daya',
  'home_my_room': 'Milikku',
  "create_room": 'Tidak, aku tidak baik',
  'login_with_password': "Aktifkan Login Kata Sandi",
  'login_with_password_disable': "Nonaktifkan login kata sandi",
  'change_password': 'Ubah Kata Sandi',
  'account_password': 'Kata Sandi Akun',
  'enter_password': "Masukkan Kata Sandi Akun" ,
  're_enter_password': 'Masukkan kembali kata sandi akun',
  'id_login': "Masuk menggunakan ID",
  'id_text': 'ID',
};