const Map<String, String> ph = {
  'about_us_title': 'Tungkol sa App',
  'about_us_version': 'Bersyon ng bersyon',
  'about_us_update_version': 'I-update ang bersyon',
  'about_us_official_website': 'Opisyal na website',
  'account_management_title': 'Pamamahala ng Account',
  'add_post': 'Mag-post',
  'add_post_msg': 'Ang iyong post ay sinusuri ng isa sa aming mga tagapangasiwa at tatanggapin ito sa lalong madaling panahon',
  'add_photo_gallery': 'Gallery ng mga larawan',
  'add_camera': 'Kamera',
  'add_status_my_status': 'Aking Katayuan',
  'add_status_share': 'Ibahagi',
  'add_status_msg': 'Matagumpay na na-update ang katayuan',
  'agreement_title': 'Kasunduan sa Paggamit',
  'agreement_user_agreement': 'Kasunduan sa Paggamit ng LikLok',
  'edit_language': 'Wika',
  'edit_arabic': 'Arabo',
  'edit_profile_title': 'I-edit ang Profile',
  'edit_profile_Cover_photo': 'Larawan ng Pabalat',
  'edit_profile_upload': 'I-upload',
  'edit_profile_basic_information': 'Pangunahing Impormasyon',
  'edit_profile_user_name': 'Pangalan ng Gumagamit',
  'edit_profile_gender': 'Kasarian',
  'edit_profile_male': 'Lalaki',
  'edit_profile_female': 'Babae',
  'edit_profile_date_of_birth': 'Petsa ng Kapanganakan',
  'edit_profile_country': 'Bansa',
  'edit_profile_my_tags': 'Aking Mga Hilig',
  'edit_profile_update': 'I-update',
  'edit_profile_tag_msg': 'Matagumpay na na-update ang iyong mga hilig',
  'edit_profile_user_name_title': 'Pangalan ng Gumagamit',
  'edit_profile_characters !': 'Maximum na 20 karakter!',
  'edit_profile_enter_user_name': 'Ipasok ang Pangalan ng Gumagamit',
  'edit_profile_cancel': 'Kanselahin',
  'edit_profile_edit': 'I-edit',
  'edit_profile_photo_msg': 'Matagumpay na na-update ang iyong larawan!',
  'edit_profile_Cover_msg': 'Matagumpay na na-update ang iyong pabalat!',
  'followers_title': 'Mga Tagasunod',
  'following_title': "Sinusundan",
  'friends_title': 'Mga Kaibigan',
  'home_party': 'Pista',
  'home_discover': 'Tuklasin',
  'inner_report': 'Ulat',
  'inner_block': 'I-block',
  'inner_basic_information': 'Pangunahing Impormasyon',
  'inner_room_gifts': 'Mga Regalo sa Silid',
  'inner_my_frames': 'Aking Mga Frame',
  'inner_cars_(Entries)': 'Mga Sasakyan (Mga Entry)',
  'login_welcome_msg': 'Maligayang pagdating sa LikLok!',
  'login_title': 'Tungkol sa Kasiyahan!',
  'login_privacy': 'Sa iyong pagrehistro sa LikLok, sumasang-ayon ka dito',
  'login_policy': 'Patakaran ng LikLok',
  'login_and': 'at',
  'login_services': 'Mga Tuntunin ng Paggamit ng LikLok',
  'mall_title': 'Tindahan',
  'mall_purchase': 'Bumili',
  'mall_msg': 'Paumanhin, wala kang sapat na ginto!',
  'moments_recommend': 'Inirerekomenda',
  'moments_mine': 'Aking Mga Post',
  'moments_follow': 'Sumunod',
  'moments_not_interested': 'Hindi Interesado',
  'moments_report': 'Ulat',
  'my_designs_days': 'Mga Araw:',
  'my_designs_use': 'Paggamit',
  'my_level_wealth': 'Ambag',
  'my_level_karizma': 'Karizma',
  'my_level_charging': 'Pag-charge',
  'my_level_current_points': 'Kasalukuyang Mga Punto',
  'my_level_next_level': 'Sa Susunod na Antas',
  'my_level_ways_to_level_up': 'Mga Paraan upang Umakyat ng Antas?',
  'my_level_send_gift': 'Magpadala ng regalo sa isang kaibigan sa chat room',
  'my_level_gold_point': '1 Ginto = 1 Punto',
  'my_level_receive': 'Tumanggap ng regalo mula sa isang kaibigan sa chat room',
  'my_level_charge_your_gold': 'I-charge ang iyong ginto!',
  'network_title': 'Diagnosis ng Network',
  'network_start': 'Simulan',
  'notification_moments': 'Mga Sandali',
  'notification_profile': 'Profile',
  'notification_charging': 'Pag-charge',
  'notification_system': 'Sistema',
  'notification_announcement': 'Anunsyo',
  'notification_setting_title': 'Mga Abiso',
  'notification_setting_private_chat': 'Pribadong Chat',
  'notification_setting_new_followers': 'Mga Bagong Tagasunod',
  'notification_setting_invitation_message': 'Mensaheng Paanyaya',
  'notification_setting_moments_notification': 'Abiso ng mga Sandali',
  'post_title': 'Nilalaman ng Sandali',
  'post_label': 'Mangyaring maging magiliw!',
  'post_msg': 'Matagumpay na naipadala ang iyong komento!',
  'privacy_policy_title': 'Patakaran sa Privacy',
  'privacy_policy': 'Patakaran sa Privacy ng LikLok',
  'profile_msg_copied': 'Nakopya ang ID!',
  'profile_visitors': 'Mga Bisita',
  'profile_gold': 'Ginto',
  'profile_diamond': 'Brilyante',
  'profile_room': 'Silid',
  'profile_gifts': 'Mga Regalo',
  'profile_level': 'Antas',
  'profile_my_posts': 'Aking Mga Post',
  'profile_my_status': 'Aking Katayuan',
  'profile_invite_friends': 'Mag-imbita ng Mga Kaibigan',
  'profile_medals': 'Mga Medalya',
  'profile_contact_us': 'Makipag-ugnay sa Amin',
  'profile_terms_of_use': 'Mga Tuntunin ng Paggamit',
  'profile_account_settings': 'Mga Setting ng Account',
  'search_user': 'Gumagamit',
  'search_label_search': 'Maghanap ng mga gumagamit ayon sa ID / Pangalan',
  'setting_title': 'Mga Setting',
  'setting_language': 'Wika',
  'setting_notification': 'Mga Abiso',
  'setting_blocked_list': 'Listahan ng mga Naka-block',
  'setting_identity_verification': 'Pag-verify ng Pagkakakilanlan',
  'setting_clear_cache': 'I-clear ang Cache',
  'setting_views': 'Tumingin',
  'taps_home': 'Bahay',
  'taps_chats': 'Chat',
  'taps_me': 'Ako',
  'add_post_label': 'Ibahagi ang iyong opinyon sa pader ng mga sandali!',
  'gift_one_or_more_user': 'Isang gumagamit o higit pa',
  'gift_all_mic_users': 'Lahat ng gumagamit ng mikropono',
  'gift_all_room_users': 'Lahat ng gumagamit sa silid',
  'gift_send_to_all_room_members': 'Ipadala sa lahat ng mga miyembro ng silid',
  'gift_send': 'Ipadala',
  'menu_theme': 'Mga Background',
  'menu_music': 'Musika',
  'menu_lucky_number': 'Masuwerteng Numero',
  'menu_dice': 'Dado',
  'menu_lucky_bag': 'Suwerteng Bag',
  'menu_settings': 'Mga Setting',
  'room_info_room_name': 'Pangalan ng Silid',
  'room_info_room_admin': 'Tagapangasiwa ng Silid',
  'room_info_room_country': 'Bansa ng Silid',
  'room_settings': 'Mga Setting ng Silid',
  'room_settings_room_title': 'Pangalan ng Silid',
  'room_settings_update': 'I-update',
  'room_settings_hello': 'Mensaheng Pagbati',
  'room_settings_room_password': 'Password ng Silid',
  'room_settings_room_admins': 'Mga Tagapangasiwa ng Silid',
  'room_settings_room_block_list': 'Listahan ng mga Ipinagbabawal',
  'chats_massage': 'Mga Mensahe',
  'chats_friends': 'Mga Kaibigan',
  'chats_event_message': 'Mga Abiso ng Aktibidad',
  'chats_club_chat_service': 'Serbisyo sa Customer',
  'chats_system_massage': 'Mga Mensahe ng Sistema',
  'room_members': "Mga Miyembro ng Silid",
  "log_out": "Mag-Log Out",
"logout_msg": "Gusto mo bang mag-logout?",
"delete_account": "Burahin ang Account",
"delete_Account_msg": "Gusto mo bang burahin ang account?",
"change_local": "Palitan ang Wika",
"change_local_msg": "Gusto mo bang palitan ang wika ng app?",
"login_phone_title": "Magrehistro gamit ang iyong Numero ng Telepono",
'login_phone_hint': "Ilagay ang iyong numero kasama ang country code",
"send_btn": "Ipadala",
"verify_btn": "Kumpirmahin",
"verify_phone_hint": "Ilagay ang activation code",
"verify_phone_title": "I-activate ang iyong Numero ng Telepono",
"room_close_keep": "I-save",
"room_close_exit": "Lumabas",
'edit_ok': 'Sang-ayon',
'add_status_label_text': '#Ibahagi ang iyong kwento sa mga kaibigan!',
'invite_invite_friends': 'Imbitahan ang iyong mga kaibigan sa LikLok at magdiwang kasama!',
'invite_copy': 'Kopyahin ang Imbitasyon na Link',
'inner_msg_followed': 'Sinundan mo ang gumagamit na ito',
'inner_msg_unfollowed': 'Inalis mo ang pagsunod sa gumagamit na ito',
'inner_msg_no_room': 'Paumanhin, walang silid ang gumagamit na ito',
'inner_msg_not_any_room': 'Paumanhin, walang silid ang gumagamit na ito',
'chat_search_friend': 'Hanapin ang iyong mga kaibigan gamit ang ID / Pangalan',
'remote_app_msg': 'Nireport mo ang gumagamit na ito!',
'remote_app_msg_error ': 'Error! May nangyaring mali',
'remote_app_msg_blocked': 'Hinarangan mo ang gumagamit na ito!',
'remote_chat_msg_failed': 'Nabigo ang pagbubukas ng silid, mangyaring makipag-ugnayan sa suporta',
'remote_design_msg_design': 'I-set ang disenyo sa default na mode',
'contact_Us_title': 'Makipag-ugnay sa Amin',
'contact_Us_club_chat': 'Kami sa LikLok ay masaya na tulungan ka at tugunan ang iyong mga kahilingan at gawing kasiya-siya ang iyong karanasan sa paggamit ng app, kaya huwag mag-atubiling makipag-ugnay sa amin kung mayroon kang anumang problema, palagi kaming nandito para sa iyo 24 na oras sa isang araw, pitong araw sa isang linggo',
'contact_Us_social_media': 'Masaya rin kaming sundan mo kami sa mga social media platforms',
'verification_title': 'Pag-verify ng Identidad',
'verification_id_card': 'Mangyaring mag-attach ng larawan ng iyong ID card',
'verification_id_face': 'Larawan ng Mukha ng ID card',
'verification_id_back': 'Larawan ng Likod ng ID card',
'verification_verify': 'Kumpirmahin',
'clear_cash_msg': 'Matagumpay na nabura ang cache',
'chats_update_data_msg': 'Matagumpay na na-update',
'event_message_title': 'Mga Mensahe ng Abiso',
'customer_service_title': 'Serbisyo sa Customer',
'delete_chat': 'Burahin ang Chat',
'block_user': 'I-block',
'user_app_blocked_title': 'Ikaw ay Na-block!',
'user_app_blocked_msg': 'Paumanhin, hindi ka makakapasok sa app dahil na-block ka sa paggamit ng mga serbisyo ng app. Maaari kang makipag-ugnay sa admin para sa karagdagang detalye.',
'recharge_gold': 'Mag-recharge ng Gold Credit',
"diamond_exchange": "Palitan ang Diamond Credit",
"diamond_exchange_inp_hint": "Ilagay ang halaga ng pagpapalit",
"diamond_exchange_note": "Ang pinakamababang halaga ng pagpapalit ay 100 diamante",
"diamond_exchange_rules": "Mga Patakaran sa Pagpapalit ng Diamante sa Ginto",
"wallet_diamond_rule1": "Ang mga regalong natanggap mo ay awtomatikong pinapalitan ng diamante sa mga itinakdang porsyento",
"wallet_diamond_rule2": "Ang porsyento ng pagpapalit ng diamante sa ginto ay",
"exchanged_gold": "Halaga ng gold na nailipat:",
"exchange_btn": "Palitan sa Ginto",
"details": "Mga Detalye",
"exchange_failed": "Hindi maipapalit ang diamante maliban kung ang halaga ay 100 diamante o higit pa",
"charging_details": "Mga Detalye ng Pag-charge",
"exchange_failed2": "Paumanhin, ang iyong balanse ng diamante ay hindi sapat",
"edit_profile_user_gender": "I-edit ang Kasarian ng Gumagamit",
"vip": "Aristokratik",
"vip_privileges": "Mga Pribilehiyo ng Aristokratik",
"Vip_package": "Pakete ng Aristokratik",
"car": "Sasakyan",
"medal": "Medalya",
"special_msg": "Mga Espesyal na Mensahe",
"entering_effect": "Epekto ng Pagpasok",
"login_time": "Itago ang Petsa ng Pagrehistro",
"stop_track": "Itigil ang Pagsubaybay",
"no_kick": "Iwasan ang Pag-kick",
"use_mic": "Sumali sa Mic",
"mic_closed_msg": "Paumanhin, nakasara ang mic na ito",
"un_use_mic": "Umalis sa Mic",
"mute": "I-mute",
"lock_mic": "I-lock ang Mic",
"lock_all_mics": "I-lock ang Lahat ng Mic",
"unlock_mic": "I-unlock ang Mic",
"unlock_all_mic": "I-unlock ang Lahat ng Mic",
'remove_from_mic': "Tanggalin mula sa Mic",
'chat_error': 'Error',
'chat_loading': 'Naglo-load',
'inner_nothing': 'Walang Nandito',
'inner_nothing_update': 'Walang Nandito, I-update ang Iyong Profile',
'login_verify_phone': 'Paumanhin, hindi namin ma-verify ang telepono ngayon!',
'login_code_msg': 'Matagumpay na naipadala ang verification code',
'network_msg': 'Lahat ng mga serbisyo sa network ay gumagana ayon sa inaasahan',
'splash_party': 'Magdiwang Hanggang Kaya',
'musics2_model_add_music': 'Magdagdag ng Musika',
'musics_model_my_music': 'Musika',
'agency_charge_title': 'Mag-recharge ng Credit ng Miyembro',
'agency_charge_operation_title': 'Mga Operasyon ng Recharge',
'agency_charge_search': 'Maghanap',
'agency_charge_charge': 'Mag-recharge',
'agency_charge_user_data': 'Data ng Gumagamit',
'join_host_title': 'Humiling ng Pagsali sa Ahensya',
'join_host_request': 'Magpadala ng Kahilingan para sa Pagsali',
'join_host_data': 'Data ng Ahensya',
'agency_income_title': 'Kita ng Host',
'agency_income_target': 'Target',
'agency_income_work_hour': 'Bilang ng Oras ng Trabaho',
'agency_income_hour': 'Oras: ',
'agency_income_day': 'Araw: ',
'agency_income_work_points': 'Bilang ng Kasalukuyang Mga Punto',
'agency_income_next_target': 'Natitira bago makamit ang susunod na target.',
'agency_income_next_achieve_target': 'Natitira para makamit ang susunod na target.',
'block_msg_unblocked': 'Na-unblock mo ang gumagamit na ito!',
'chat_hint_text_form': 'Sumulat ng isang bagay...',
'chat_no_resents': 'Walang kasalukuyan',
'room_close_mic': 'Paumanhin, nakasara ang mikropono na ito',
'room_msg': "Nais ng Pamunuan ng LikLok na magkaroon ka ng masayang oras sa kanilang platform at binibigyang-diin ang kahalagahan ng pagpapanatili ng magandang asal sa pakikipag-usap sa lahat ng miyembro at iwasan ang pang-aabala, at nagbabala sa pagtukoy sa mga sensitibong paksa sa politika at relihiyon.",
"notice": "Pagpasok sa silid: ",
"user_enter_message": "Kamusta...",
"host_agency_search": "Maghanap gamit ang ID ng Ahensya",
"request_process": "Pinoproseso ang iyong kahilingan ngayon",
"agency_members_title": "Mga Miyembro ng Ahensya",
"choose_receiver": "Dapat mong tukuyin ang tatanggap ng regalo muna",
"choose_gift": "Mangyaring pumili ng regalo",
"daily": "Araw-araw",
"weekly": "Lingguhan",
"monthly": "Buwanang",
"app_rank": "Ranking ng LikLok",
"room_remove_mic": "Paumanhin, inalis ka ng admin mula sa mic",
"music_error_permissions": "Hindi ma-upload ang mga file ng musika nang walang pahintulot sa pag-access sa mga file",
"unmute": "I-play ang Tunog",
"room_settings_room_subject": "Uri ng Silid",
"room_settings_room_img": "Larawan ng Silid",
"room_password_label": "Password ng Silid",
"room_password_wrong": "Maling Password",
"show_profile": "Ipakita ang Gumagamit",
"admin_mic_alert": "Paumanhin! Mic na para lamang sa mga admin",
"should_be_on_mic": "Paumanhin, dapat kang maging gumagamit ng mic!",
"add_admin": "Admin",
"add_admin_title": "Magdagdag ng Admin sa Silid",
"admin_added": "Naitakdang bagong Admin",
"remove_btn": "Burahin",
"admin_deleted": "Nabura ang Admin",
"room_save_dialog_title": "I-cancel ang Pag-save ng Silid",
"room_save_dialog_msg": "Gusto mo bang i-cancel ang pag-save ng silid?",
"show_user": "Ipakita ang Gumagamit",
"counter_off": "Naka-off ang Counter",
"counter_on": "Naka-on ang Counter",
"kick_out": "Kick Out",
"kick_out_hour": "Kick Out sa loob ng Isang Oras",
"kick_out_day": "Kick Out sa loob ng Isang Araw",
"kick_out_forever": "Permanenteng Kick Out",
"local_lucky_case": "Local Lucky Case",
"global_lucky_case": "Global Lucky Case",
"benner_global_hint": "Ipapakita ang Global Lucky Case sa lahat ng silid",
"benner_global_hint2": "Anumang tao ay maaaring buksan ang kahon at makakuha ng ginto",
"benner_local_hint": "Ipapakita ang Local Lucky Case sa loob ng silid",
"lucky_case_msg": "Nakuha mo mula sa Lucky Case ang",
"rollet_value": "Bayad sa Pagpasok",
"rollet_max_members": "Pinakamataas na Bilang ng mga Miyembro",
"rollet_admin_play": "Kasali rin ako",
"rollet_start": "Simulan",
"rollet_hint_text": "Kailangan ng hindi bababa sa dalawang tao upang simulan ang laro at hindi maaaring sumali ang iba pagkatapos simulan ang laro",
"rollet_join": "Sumali",
"no_active_rollet": "Walang aktibong rolet sa kasalukuyan",
"kickout_msg": "Na-kick out ka mula sa silid ng admin",
"room_blocked_msg": "Paumanhin, hindi ka makapasok sa silid sa kasalukuyan",
"unblock_btn": "I-unblock",
"invite_link_copied": "Nakopya ang link ng imbitasyon sa app",
"current_target": "Kasalukuyang Target",
"non": "(Hindi Tukuyin)",
"next_target": "Susunod na Target",
"total_work_hours": "Kabuuang Bilang ng Oras ng Trabaho",
"total_work_days": "Kabuuang Bilang ng Araw ng Trabaho",
"salary": "Kasalukuyang Sahod",
"check_privacy": "Mangyaring sumang-ayon sa Patakaran sa Privacy muna",
"no_data": "Walang data na ipapakita!",
"help_title": "Sentro ng Tulong",
"help_center_whatssapp": "Ipadala ang iyong katanungan sa pamamagitan ng WhatsApp",
"help_center_website": "Maaari mong bisitahin ang aming website para sa mas mahusay na serbisyo",
"help_center_email": "O maaari kang makakuha ng suporta sa pamamagitan ng email",
"read_more": "Magbasa Pa",
"account_ban_title": "Na-ban ang Iyong Account",
"account_ban_msg": "Paumanhin, hindi ka pinapayagang pumasok sa app gamit ang account na ito dahil na-ban ang iyong account dahil sa paglabag sa mga tuntunin ng paggamit",
"device_ban_title": "Na-ban ang Iyong Telepono",
"device_ban_msg": "Paumanhin, hindi ka pinapayagang pumasok sa app gamit ang teleponong ito dahil na-ban ang iyong device dahil sa paglabag sa mga tuntunin ng paggamit",
"charge_title": "Recharge",
"get_8000_coins": "Kumuha ng 8000 unit ng ginto para sa 1 dolyar lamang",
"get_40000_coins": "Kumuha ng 40000 unit ng ginto para sa 5 dolyar lamang",
"get_160000_coins": "Kumuha ng 160000 unit ng ginto para sa 20 dolyar lamang",
"get_400000_coins": "Kumuha ng 400000 unit ng ginto para sa 50 dolyar lamang",
"get_800000_coins": "Kumuha ng 800000 unit ng ginto para sa 100 dolyar lamang",
"new_joiner": "Tanggapin ang Pagsali",
"kik_member": "I-kick out ang Miyembro",
"out_member": "Na-kick out na Miyembro",
"accept_member_title": "Tanggapin ang Pagsali ng Miyembro",
"accept_member_msg": "Gusto mo bang tanggapin ang pagsali ng miyembro?",
"kik_member_title": "I-kick out ang Miyembro",
"kik_member_msg": "Gusto mo bang i-kick out ang miyembrong ito?",
"moments": "Mga Sandali",
"chats": "Mga Mensahe",
"me": "Ako",
"game1": "Bato, Papel, Gunting",
"balance_added": "Matagumpay na naidagdag ang balanse",
"agency_statics_title": "Statistika ng Ahensya",
"day_count": "Bilang ng mga Araw",
"point_count": "Bilang ng mga Punto",
"agent_salary": "Sahod ng Ahente",
"host_agent": "Sahod ng Host",
  'indian_lang': 'wikang Hindi',
  'phlpini_lang': 'wikang Filipino',
  'pangladish_lang': 'wikang Bengali',
  'barazil_lang': 'wikang Brazilian (Portuguese)',
  'france_lang': 'Pranses',
  'games': 'Mga laro',
  'chineese_lang':'wikang Tsino',
  'indonisian_lang':'Indonesian',


};